"""Renders mosquitto ACL and TLS listener configuration from the station registry.

Certificate CN (= station serial) is the mosquitto username
(``use_identity_as_username true``).  Topics follow MQTT_TLS_ICD v0.1:
``zs/v1/{tenant}/{station_id}/{up|status|down|ack|receipt}``.
"""

from __future__ import annotations

from .registry import Registry, StationRow

BRIDGE_USER = "bridge"


def station_topics(row: StationRow) -> list[tuple[str, str]]:
    base = f"zs/v1/{row.tenant}/{row.station_id}"
    return [
        ("write", f"{base}/up"),
        ("write", f"{base}/status"),
        ("read", f"{base}/down"),
        ("write", f"{base}/ack"),
        ("read", f"{base}/receipt"),
    ]


def render_acl(registry: Registry, bridge_user: str = BRIDGE_USER) -> str:
    lines = [
        "# Generated by server/pki: do not edit by hand, run `python -m pki.cli mosquitto-acl`.",
        "# Certificate CN is the MQTT username (use_identity_as_username true).",
        "# Stations without an active certificate get no entry and are refused by the ACL.",
        "",
        f"user {bridge_user}",
    ]
    tenants = sorted({r.tenant for r in registry.active()})
    for tenant in tenants:
        lines += [
            f"topic read zs/v1/{tenant}/+/up",
            f"topic read zs/v1/{tenant}/+/status",
            f"topic write zs/v1/{tenant}/+/down",
            f"topic read zs/v1/{tenant}/+/ack",
            f"topic write zs/v1/{tenant}/+/receipt",
        ]
    lines.append("")
    for row in registry.active():
        lines.append(f"user {row.serial}")
        for access, topic in station_topics(row):
            lines.append(f"topic {access} {topic}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_listener_conf(cert_dir: str = "/mosquitto/certs", crl: bool = True) -> str:
    conf = [
        "persistence true",
        "persistence_location /mosquitto/data/",
        "log_dest stdout",
        "listener 8883 0.0.0.0",
        "protocol mqtt",
        "allow_anonymous false",
        f"cafile {cert_dir}/ca-chain.pem",
        f"certfile {cert_dir}/server.crt.pem",
        f"keyfile {cert_dir}/server.key.pem",
        "require_certificate true",
        "use_identity_as_username true",
        "tls_version tlsv1.2",
    ]
    if crl:
        conf.append(f"crlfile {cert_dir}/crl.pem")
    conf += ["", "acl_file /mosquitto/config/station_acl.conf"]
    return "\n".join(conf) + "\n"
