"""Renders mosquitto ACL and TLS listener configuration from the station registry.

Certificate CN (= station serial) is the mosquitto username
(``use_identity_as_username true``).  Topics follow MQTT_TLS_ICD v0.1:
``zs/v1/{tenant}/{station_id}/{up|status|down|ack|receipt|audio|fwreq|fw|bearing}`` (audio: addendum B, fwreq/fw:
addendum F, bearing: addendum H).  The output API dioneya.alert/1 (protocols/DIONEYA_ALERT_API_v1.md, 4.4) is
published by the bridge user to ``dioneya/alert/v1/{tenant}``; a registered consumer (CN = its name) reads the
topics of its tenants.
"""

from __future__ import annotations

from .registry import Registry, StationRow

BRIDGE_USER = "bridge"
BENCH_BRIDGE_USER = "bridge-bench"
ALERT_TOPIC_PREFIX = "dioneya/alert/v1"          # integration/mqtt_alerts.TOPIC_PREFIX


def alert_topic(tenant: str) -> str:
    return f"{ALERT_TOPIC_PREFIX}/{tenant}"


def station_topics(row: StationRow) -> list[tuple[str, str]]:
    base = f"zs/v1/{row.tenant}/{row.station_id}"
    return [
        ("write", f"{base}/up"),
        ("write", f"{base}/status"),
        ("read", f"{base}/down"),
        ("write", f"{base}/ack"),
        ("read", f"{base}/receipt"),
        ("write", f"{base}/audio"),
        ("write", f"{base}/fwreq"),
        ("read", f"{base}/fw"),
        ("write", f"{base}/bearing"),
    ]


def render_acl(registry: Registry, bridge_user: str = BRIDGE_USER) -> str:
    lines = [
        "# Generated by server/pki: do not edit by hand, run `python -m pki.cli mosquitto-acl`.",
        "# Certificate CN is the MQTT username (use_identity_as_username true).",
        "# Stations without an active certificate get no entry and are refused by the ACL.",
        "",
        f"user {bridge_user}",
    ]
    consumers = registry.consumers(status="active")
    tenants = sorted({r.tenant for r in registry.active()} | {t for c in consumers for t in c.tenants})
    for tenant in tenants:
        lines += [
            f"topic read zs/v1/{tenant}/+/up",
            f"topic read zs/v1/{tenant}/+/status",
            f"topic write zs/v1/{tenant}/+/down",
            f"topic read zs/v1/{tenant}/+/ack",
            f"topic write zs/v1/{tenant}/+/receipt",
            f"topic read zs/v1/{tenant}/+/audio",
            f"topic read zs/v1/{tenant}/+/fwreq",
            f"topic write zs/v1/{tenant}/+/fw",
            f"topic read zs/v1/{tenant}/+/bearing",
            f"topic write {alert_topic(tenant)}",
        ]
    lines.extend(["", f"user {BENCH_BRIDGE_USER}"])
    for access, topic in (
        ("read", "zs/v1/bench/+/up"),
        ("read", "zs/v1/bench/+/status"),
        ("write", "zs/v1/bench/+/down"),
        ("read", "zs/v1/bench/+/ack"),
        ("write", "zs/v1/bench/+/receipt"),
        ("read", "zs/v1/bench/+/audio"),
        ("read", "zs/v1/bench/+/fwreq"),
        ("write", "zs/v1/bench/+/fw"),
        ("read", "zs/v1/bench/+/bearing"),
        ("write", alert_topic("bench")),
    ):
        lines.append(f"topic {access} {topic}")
    lines.append("")
    for row in registry.active():
        lines.append(f"user {row.serial}")
        for access, topic in station_topics(row):
            lines.append(f"topic {access} {topic}")
        lines.append("")
    for consumer in consumers:                   # the output API: a consumer reads the alert topics of its tenants
        lines.append(f"user {consumer.name}")
        for tenant in consumer.tenants:
            lines.append(f"topic read {alert_topic(tenant)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_listener_conf(cert_dir: str = "/mosquitto/certs", crl: bool = True) -> str:
    conf = [
        "persistence true",
        "persistence_location /mosquitto/data/",
        "log_dest stdout",
        "listener 8883 0.0.0.0",
        "protocol mqtt",
        "allow_anonymous false",
        f"cafile {cert_dir}/ca-chain.pem",
        f"certfile {cert_dir}/server.crt.pem",
        f"keyfile {cert_dir}/server.key.pem",
        "require_certificate true",
        "use_identity_as_username true",
        "tls_version tlsv1.2",
    ]
    if crl:
        conf.append(f"crlfile {cert_dir}/crl.pem")
    conf += ["", "acl_file /mosquitto/config/station_acl.conf",
             "", "# consumers of the output API (dioneya.alert/1) with a persistent session get what was published while",
             "# they were away: this many QoS 1 messages are kept per client, the session for a week",
             "max_queued_messages 10000", "persistent_client_expiration 7d"]
    return "\n".join(conf) + "\n"
