#ifndef ZS_FFT_MIXED_H
#define ZS_FFT_MIXED_H

/*
 * Float32 mixed-radix (4/5/2) FFT for the MCU feature pipeline.
 *
 * Replaces the recursive per-sample cosf/sinf FFT of zs_dsp.c with the same
 * decimation-in-time structure but twiddles generated by rotation with a
 * periodic re-synchronisation, and a real-input transform that packs the
 * 32000-sample window into a 16000-point complex FFT.  Two real transforms:
 * the out-of-place one needs `work` (n/2 complex) + `mag` (n floats, also the
 * packed input) = 256 KB for n = 32000; the in-place one (iterative
 * decimation in frequency, digit-reversed read-out) needs `work` (n/2 complex)
 * + `mag` (n/2 + 1 floats) = 192 KB and is what the MCU extractor uses.  Any n
 * whose prime factors are 2 and 5 is supported (32000 = 2^8 * 5^3, 8192, ...).
 *
 * Portable/host only, no allocation, no double.
 */

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "zs_fft.h"

/* Sample provider for the real transform: returns x[i] (already windowed/normalised). */
typedef float (*zs_fft_sample_fn_t)(const void *ctx, unsigned i);

/* True when n = 2^a * 5^b, n >= 2 (radix schedule 4,4,...,5,5,2). */
bool zs_fft_mixed_supported(unsigned n);

/*
 * In-place complex FFT of x[0..n) (forward, e^{-2 pi i kn/N}, no scaling).
 * `scratch` must hold n complex values; it is used as the working buffer and
 * on return x holds the spectrum.
 */
bool zs_fft_mixed_complex(zs_complex_t *x, zs_complex_t *scratch, unsigned n);

/*
 * Real FFT of an n-sample signal delivered through `sample` (n even, n/2
 * mixed-radix supported).  `work` must hold n/2 complex values and `mag` at
 * least n floats (it doubles as the packed input buffer).  On return
 * `mag[k]` = |X_k| for k = 0..n/2 (n/2+1 values), `max_mag` the maximum.
 * X_k follows the same definition as the host zs_dsp global spectrum.
 */
bool zs_fft_mixed_real_magnitude(zs_fft_sample_fn_t sample, const void *ctx, unsigned n,
                                 zs_complex_t *work, float *mag, float *max_mag);

/*
 * Same result with the packed input and the spectrum both in `work` (n/2 complex,
 * in-place decimation in frequency); `mag` needs only n/2 + 1 floats.  Same
 * twiddle scheme, so the magnitudes match the out-of-place transform to float
 * rounding (test_fft_mixed).
 */
bool zs_fft_mixed_real_magnitude_inplace(zs_fft_sample_fn_t sample, const void *ctx, unsigned n,
                                         zs_complex_t *work, float *mag, float *max_mag);

#endif
