#include "zs_bg95.h"
#include <string.h>
#include <stdio.h>
static void send_cmd(zs_bg95_t *m,const char *s){if(!m||!s||!m->io.uart_write)return;size_t n=strlen(s);if(n>=sizeof(m->last_command)-3)n=sizeof(m->last_command)-3;memcpy(m->last_command,s,n);m->last_command[n]=0;uint8_t b[128];memcpy(b,s,n);b[n++]='\r';b[n++]='\n';m->io.uart_write(m->io.ctx,m->uart_channel,b,n);m->command_pending=true;}
void zs_bg95_init(zs_bg95_t *m,const zs_hal_port_t *io,unsigned uart,unsigned pwrkey,const char *apn){if(!m)return;memset(m,0,sizeof(*m));if(io)m->io=*io;m->uart_channel=uart;m->pwrkey_gpio=pwrkey;m->state=ZS_BG95_OFF;if(apn)strncpy(m->apn,apn,sizeof(m->apn)-1);}
void zs_bg95_power_on(zs_bg95_t *m,uint32_t now){if(!m)return;if(m->io.gpio_write)m->io.gpio_write(m->io.ctx,m->pwrkey_gpio,true);m->state=ZS_BG95_POWERING;m->deadline_ms=now+700;m->retries=0;m->network=ZS_BG95_NET_NONE;}
static void next_after_ok(zs_bg95_t*m,uint32_t now){m->command_pending=false;m->retries=0;switch(m->state){case ZS_BG95_AT_SYNC:m->state=ZS_BG95_SIM_CHECK;send_cmd(m,"AT+CPIN?");break;case ZS_BG95_CONFIGURE:m->state=ZS_BG95_REGISTERING;send_cmd(m,"AT+CEREG?");break;default:(void)now;break;}}
static int regstat(const char *line){const char *p=strrchr(line,',');if(!p)p=strchr(line,':');if(!p)return -1;while(*p&&(*p==','||*p==':'||*p==' '))p++;return (*p>='0'&&*p<='9')?*p-'0':-1;}
void zs_bg95_on_line(zs_bg95_t*m,const char*line,uint32_t now){if(!m||!line)return;if(strstr(line,"+CPIN: READY")){m->sim_ready=true;m->state=ZS_BG95_CONFIGURE;char c[100];if(m->apn[0])snprintf(c,sizeof(c),"AT+CGDCONT=1,\"IP\",\"%s\"",m->apn);else strcpy(c,"ATE0");send_cmd(m,c);return;}if(strstr(line,"+CEREG:")){int s=regstat(line);m->registered_eps=(s==1||s==5);if(m->registered_eps){m->network=ZS_BG95_NET_LTE;m->state=ZS_BG95_READY;m->command_pending=false;}return;}if(strstr(line,"+CREG:")){int s=regstat(line);m->registered_cs=(s==1||s==5);if(m->registered_cs){m->network=ZS_BG95_NET_2G;m->state=ZS_BG95_READY;m->command_pending=false;}return;}if(strcmp(line,"OK")==0){next_after_ok(m,now);return;}if(strstr(line,"ERROR")){m->command_pending=false;if(++m->retries>3)m->state=ZS_BG95_ERROR;else m->retry_at_ms=now+1000;}}
void zs_bg95_tick(zs_bg95_t*m,uint32_t now){if(!m)return;if(m->state==ZS_BG95_POWERING&&now>=m->deadline_ms){if(m->io.gpio_write)m->io.gpio_write(m->io.ctx,m->pwrkey_gpio,false);m->state=ZS_BG95_AT_SYNC;m->retry_at_ms=now;}if(m->state==ZS_BG95_AT_SYNC&&!m->command_pending&&now>=m->retry_at_ms){send_cmd(m,"AT");m->retry_at_ms=now+1000;}if(m->state==ZS_BG95_REGISTERING&&!m->command_pending&&now>=m->retry_at_ms){if(m->retries<5){send_cmd(m,"AT+CEREG?");m->retries++;m->retry_at_ms=now+2000;}else{send_cmd(m,"AT+CREG?");m->retry_at_ms=now+2000;}}}
bool zs_bg95_ready(const zs_bg95_t*m){return m&&m->state==ZS_BG95_READY;}
const char*zs_bg95_state_name(zs_bg95_state_t s){static const char*n[]={"OFF","POWERING","AT_SYNC","SIM_CHECK","CONFIGURE","REGISTERING","READY","ERROR"};return s<=ZS_BG95_ERROR?n[s]:"?";}
