#include "zs_dsp.h"
#include "zs_fft.h"
#include <math.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
#define SR 32000u
#define NSAMP 32000u
#define N_GLOBAL 32000u
#define GLOBAL_BINS (N_GLOBAL/2u+1u)
#define STFT_N 2048u
#define STFT_HOP 512u
#define STFT_BINS (STFT_N/2u+1u)
#define STFT_FRAMES 63u
#define N_MELS 128u
#define N_MFCC 13u
#define YIN_FRAMES 32u
#define MAX_HARMONICS 64u
static zs_complex_t g_fft[N_GLOBAL];static float g_mag[GLOBAL_BINS];static float g_mel[STFT_FRAMES][N_MELS];static float g_yin[801u];static float g_f0[YIN_FRAMES];static float g_harmonics[MAX_HARMONICS];static int g_peaks[GLOBAL_BINS];static uint8_t g_peak_state[GLOBAL_BINS];static const float *g_peak_cmp_mag;
static float clamp01(float x){return x<0.0f?0.0f:(x>1.0f?1.0f:x);}static float sample_norm(const int16_t *pcm,int idx,float dc,float scale){if(idx<0||idx>=(int)NSAMP)return 0.0f;return (((float)pcm[idx])-dc)*scale;}static float sample_edge(const int16_t *pcm,int idx,float dc,float scale){if(idx<0)idx=0;else if(idx>=(int)NSAMP)idx=(int)NSAMP-1;return (((float)pcm[idx])-dc)*scale;}static float hann(unsigned i,unsigned n){return 0.5f-0.5f*cosf(2.0f*(float)M_PI*(float)i/(float)n);}static float magc(zs_complex_t z){return sqrtf(z.re*z.re+z.im*z.im);}
static float hz_to_mel(float hz){const float f_sp=200.0f/3.0f;float m=hz/f_sp;if(hz>=1000.0f){const float min_log_mel=1000.0f/f_sp;const float logstep=logf(6.4f)/27.0f;m=min_log_mel+logf(hz/1000.0f)/logstep;}return m;}static float mel_to_hz(float mel){const float f_sp=200.0f/3.0f;const float min_log_mel=1000.0f/f_sp;const float logstep=logf(6.4f)/27.0f;if(mel>=min_log_mel)return 1000.0f*expf(logstep*(mel-min_log_mel));return f_sp*mel;}
static void sort_small(float*a,unsigned n){for(unsigned i=1;i<n;i++){float v=a[i];int j=(int)i-1;while(j>=0&&a[j]>v){a[j+1]=a[j];j--;}a[j+1]=v;}}static float median_small(float*a,unsigned n){if(!n)return 0.0f;sort_small(a,n);return(n&1u)?a[n/2u]:0.5f*(a[n/2u-1u]+a[n/2u]);}
static void fswap(float*a,float*b){float t=*a;*a=*b;*b=t;}static float quickselect(float*a,unsigned n,unsigned k){unsigned l=0,r=n-1;for(;;){if(l==r)return a[l];float pivot=a[l+(r-l)/2u];unsigned i=l,j=r;while(i<=j){while(a[i]<pivot)i++;while(a[j]>pivot){if(j==0)break;j--;}if(i<=j){fswap(&a[i],&a[j]);i++;if(j==0)break;j--;}}if(k<=j)r=j;else if(k>=i)l=i;else return a[k];}}
static float exact_median_normalized(const float*a,unsigned i0,unsigned i1,float maxv){if(maxv<=0.0f||i1<=i0)return 0.0f;float*tmp=(float*)g_fft;unsigned n=i1-i0;for(unsigned j=0;j<n;j++)tmp[j]=a[i0+j]/maxv;if(n&1u)return quickselect(tmp,n,n/2u);float hi=quickselect(tmp,n,n/2u);float lo=tmp[0];for(unsigned i=1;i<n/2u;i++)if(tmp[i]>lo)lo=tmp[i];return 0.5f*(lo+hi);}static int cmp_peak_height_desc(const void*aa,const void*bb){const int a=*(const int*)aa,b=*(const int*)bb;const float da=g_peak_cmp_mag[a],db=g_peak_cmp_mag[b];if(da<db)return 1;if(da>db)return-1;return b-a;}
static void preprocess_stats(const int16_t*pcm,float*dc,float*scale,float*energy,float*rms,float*zcr){double mean=0.0;for(unsigned i=0;i<NSAMP;i++)mean+=pcm[i];mean/=NSAMP;float peak=0.0f;for(unsigned i=0;i<NSAMP;i++){float v=fabsf((float)pcm[i]-(float)mean);if(v>peak)peak=v;}float sc=peak>1e-9f?1.0f/peak:1.0f;double e=0.0;unsigned crossings=0;float prev=((float)pcm[0]-(float)mean)*sc;for(unsigned i=0;i<NSAMP;i++){float y=((float)pcm[i]-(float)mean)*sc;e+=(double)y*y;if(i&&((y>=0.0f)!=(prev>=0.0f)))crossings++;prev=y;}*dc=(float)mean;*scale=sc;*energy=(float)(e/NSAMP);*rms=sqrtf(*energy);*zcr=(float)crossings/(float)(NSAMP-1u);}
static void fft32000_rec(zs_complex_t*out,const int16_t*pcm,float dc,float scale,unsigned offset,unsigned stride,unsigned n){if(n==1u){out[0].re=sample_norm(pcm,(int)offset,dc,scale)*hann(offset,NSAMP);out[0].im=0.0f;return;}unsigned r=(n%4u==0u)?4u:((n%5u==0u)?5u:2u),m=n/r;for(unsigned p=0;p<r;p++)fft32000_rec(out+p*m,pcm,dc,scale,offset+p*stride,stride*r,m);for(unsigned k=0;k<m;k++){zs_complex_t a[5],res[5];float theta=-2.0f*(float)M_PI*(float)k/(float)n;float br=cosf(theta),bi=sinf(theta),wr=1.0f,wi=0.0f;for(unsigned p=0;p<r;p++){zs_complex_t v=out[p*m+k];a[p].re=v.re*wr-v.im*wi;a[p].im=v.re*wi+v.im*wr;float nwr=wr*br-wi*bi;wi=wr*bi+wi*br;wr=nwr;}for(unsigned q=0;q<r;q++){float qr=cosf(-2.0f*(float)M_PI*(float)q/(float)r),qi=sinf(-2.0f*(float)M_PI*(float)q/(float)r);float pr=1.0f,pi=0.0f,sr=0.0f,si=0.0f;for(unsigned p=0;p<r;p++){sr+=a[p].re*pr-a[p].im*pi;si+=a[p].re*pi+a[p].im*pr;float npr=pr*qr-pi*qi;pi=pr*qi+pi*qr;pr=npr;}res[q].re=sr;res[q].im=si;}for(unsigned q=0;q<r;q++)out[q*m+k]=res[q];}}
static bool global_spectrum(const int16_t*pcm,float dc,float scale,float*max_mag){fft32000_rec(g_fft,pcm,dc,scale,0u,1u,N_GLOBAL);float mx=0.0f;for(unsigned i=0;i<GLOBAL_BINS;i++){float m=magc(g_fft[i]);g_mag[i]=m;if(m>mx)mx=m;}*max_mag=mx;return true;}
static float f0_one_frame(const int16_t*pcm,int start,float dc,float scale){enum{YFFT=8192,MINP=64,MAXP=800};float cumulative_energy[MAXP+1];double run_e=0.0;for(unsigned i=0;i<4096u;i++){float y=sample_norm(pcm,start+(int)i,dc,scale);g_fft[i].re=y;g_fft[i].im=0.0f;run_e+=(double)y*y;if(i<=MAXP)cumulative_energy[i]=(float)run_e;}for(unsigned i=4096u;i<YFFT;i++){g_fft[i].re=0.0f;g_fft[i].im=0.0f;}if(!zs_fft_radix2(g_fft,YFFT))return 0.0f;for(unsigned i=0;i<YFFT;i++){float p=g_fft[i].re*g_fft[i].re+g_fft[i].im*g_fft[i].im;g_fft[i].re=p;g_fft[i].im=0.0f;}if(!zs_ifft_radix2(g_fft,YFFT))return 0.0f;float acf0=g_fft[0].re;float d[MAXP+1];d[0]=0.0f;for(unsigned k=1;k<=MAXP;k++)d[k]=2.0f*(acf0-g_fft[k].re)-cumulative_energy[k-1u];double cum=0.0;for(unsigned k=1;k<=MAXP;k++){cum+=d[k];g_yin[k]=(cum>1e-30)?d[k]*(float)k/(float)cum:1.0f;}unsigned best=MINP;float bestv=g_yin[MINP];bool found=false;if(g_yin[MINP]<g_yin[MINP+1]&&g_yin[MINP]<0.1f){best=MINP;found=true;}for(unsigned k=MINP+1u;!found&&k<MAXP;k++){bool trough=(g_yin[k]<g_yin[k-1u]&&g_yin[k]<=g_yin[k+1u]);if(g_yin[k]<bestv){bestv=g_yin[k];best=k;}if(trough&&g_yin[k]<0.1f){best=k;found=true;}}if(!found&&g_yin[MAXP]<bestv)best=MAXP;float shift=0.0f;if(best>MINP&&best<MAXP){float a=g_yin[best-1u],b=g_yin[best],c=g_yin[best+1u];float den=a-2.0f*b+c;if(fabsf(den)>1e-20f){float q=0.5f*(a-c)/den;if(fabsf(q)<=1.0f)shift=q;}}float period=(float)best+shift;return period>0.0f?(float)SR/period:0.0f;}
static unsigned estimate_f0_track(const int16_t*pcm,float dc,float scale,float*median,float*variation){unsigned n=0;for(unsigned fr=0;fr<YIN_FRAMES;fr++){int start=(int)(fr*1024u)-2048;float f=f0_one_frame(pcm,start,dc,scale);if(f>0.0f)g_f0[n++]=f;}if(!n){*median=0.0f;*variation=0.0f;return 0;}float tmp[YIN_FRAMES];memcpy(tmp,g_f0,n*sizeof(float));*median=median_small(tmp,n);if(n<2){*variation=0.0f;return n;}double s=0.0,ss=0.0;for(unsigned i=0;i<n;i++){s+=g_f0[i];ss+=(double)g_f0[i]*g_f0[i];}double mean=s/n,var=ss/n-mean*mean;if(var<0)var=0;*variation=(fabs(mean)>1e-12)?clamp01((float)(sqrt(var)/fabs(mean))):0.0f;return n;}
static float spectral_f0_fallback(float max_mag){if(max_mag<=0.0f)return 0.0f;unsigned lo=(unsigned)ceilf(40.0f*(float)N_GLOBAL/(float)SR),hi=(unsigned)floorf(500.0f*(float)N_GLOBAL/(float)SR),bi=lo;float bm=0.0f;for(unsigned i=lo;i<=hi;i++)if(g_mag[i]>bm){bm=g_mag[i];bi=i;}return(float)bi*(float)SR/(float)N_GLOBAL;}
static unsigned detect_harmonics(float f0,float max_mag,float*step,float*variation){if(f0<=0.0f||max_mag<=0.0f){*step=0.0f;*variation=1.0f;return 0;}const float df=(float)SR/(float)N_GLOBAL;unsigned band0=(unsigned)ceilf((f0*0.7f)/df),band1=(unsigned)floorf(12000.0f/df);if(band1>=GLOBAL_BINS)band1=GLOBAL_BINS-1u;float med=exact_median_normalized(g_mag,band0,band1+1u,max_mag);float prominence_req=fmaxf(0.015f,med*4.0f);unsigned np=0;for(unsigned i=band0+1u;i<band1;){if(g_mag[i-1u]<g_mag[i]){unsigned j=i+1u;while(j<=band1&&g_mag[j]==g_mag[i])j++;if(j<=band1&&g_mag[j]<g_mag[i])g_peaks[np++]=(int)((i+j-1u)/2u);i=j;}else i++;}memset(g_peak_state,0,GLOBAL_BINS);g_peak_cmp_mag=g_mag;qsort(g_peaks,np,sizeof(int),cmp_peak_height_desc);unsigned distance=(unsigned)fmaxf(1.0f,floorf((f0/df)*0.45f));for(unsigned j=0;j<np;j++){int p=g_peaks[j];if(g_peak_state[p])continue;g_peak_state[p]=2;int lo=p-(int)distance+1,hi=p+(int)distance-1;if(lo<(int)band0)lo=(int)band0;if(hi>(int)band1)hi=(int)band1;for(int q=lo;q<=hi;q++)if(q!=p&&g_peak_state[q]==0)g_peak_state[q]=1;}np=0;for(unsigned p=band0+1u;p<band1;p++)if(g_peak_state[p]==2)g_peaks[np++]=(int)p;unsigned nw=0;for(unsigned j=0;j<np;j++){int p=g_peaks[j];float peak=g_mag[p]/max_mag,left_min=peak,right_min=peak;int q=p;while(q>(int)band0){q--;float v=g_mag[q]/max_mag;if(v>peak)break;if(v<left_min)left_min=v;}q=p;while(q<(int)band1){q++;float v=g_mag[q]/max_mag;if(v>peak)break;if(v<right_min)right_min=v;}float prom=peak-fmaxf(left_min,right_min);if(prom>=prominence_req)g_peaks[nw++]=p;}np=nw;bool no_peaks=(np==0);unsigned n=0,max_idx=(unsigned)floorf(12000.0f/f0);for(unsigned hi=1;hi<=max_idx&&n<MAX_HARMONICS;hi++){float target=(float)hi*f0,tol=fmaxf(5.0f,f0*0.08f);int best=-1;float bm=-1.0f;for(unsigned j=0;j<np;j++){float pf=(float)g_peaks[j]*df;if(fabsf(pf-target)<=tol&&g_mag[g_peaks[j]]>bm){bm=g_mag[g_peaks[j]];best=g_peaks[j];}}if(best>=0)g_harmonics[n++]=(float)best*df;}if(no_peaks&&n==0){g_harmonics[0]=f0;n=1;}if(n>=2){float dif[MAX_HARMONICS];for(unsigned i=1;i<n;i++)dif[i-1]=g_harmonics[i]-g_harmonics[i-1];float tmp[MAX_HARMONICS];memcpy(tmp,dif,(n-1)*sizeof(float));*step=median_small(tmp,n-1);if(n>=3){double ss=0,sx=0;for(unsigned i=0;i<n-1;i++){sx+=dif[i];ss+=(double)dif[i]*dif[i];}double mean=sx/(n-1),v=ss/(n-1)-mean*mean;if(v<0)v=0;*variation=clamp01((float)(sqrt(v)/f0));}else *variation=0.0f;}else{*step=f0;*variation=0.0f;}return n;}
static void global_features(float max_mag,float*noise_floor,float*high_band,float*roughness){if(max_mag<=0.0f){*noise_floor=*high_band=*roughness=0.0f;return;}float df=(float)SR/(float)N_GLOBAL;unsigned n0=(unsigned)ceilf(3000.0f/df);*noise_floor=exact_median_normalized(g_mag,n0,GLOBAL_BINS,max_mag);double total=0.0,band=0.0;for(unsigned i=1;i<GLOBAL_BINS;i++){float f=i*df,p=g_mag[i]*g_mag[i];if(f>20.0f)total+=p;if(f>=6000.0f&&f<=10000.0f)band+=p;}*high_band=total>1e-20?clamp01((float)(band/total)):0.0f;unsigned r0=(unsigned)ceilf(50.0f/df),r1=(unsigned)floorf(10000.0f/df);double acc=0.0;unsigned c=0;float local_max=0.0f;for(unsigned i=r0;i<=r1;i++)if(g_mag[i]>local_max)local_max=g_mag[i];if(local_max>0.0f){for(unsigned i=r0+1;i<=r1;i++){acc+=fabs((double)g_mag[i]/local_max-(double)g_mag[i-1]/local_max);c++;}}*roughness=c?clamp01((float)(acc/c)*35.0f):0.0f;}
static void stft_and_mfcc(const int16_t*pcm,float dc,float scale,float*zcr_frame_mean,float*centroid_mean,float*flatness_mean,float*bandwidth_mean,float mfcc_mean[N_MFCC],float mfcc_std[N_MFCC]){float mel_edges[N_MELS+2u];float mel0=hz_to_mel(0.0f),mel1=hz_to_mel((float)SR*0.5f);for(unsigned i=0;i<N_MELS+2u;i++)mel_edges[i]=mel_to_hz(mel0+(mel1-mel0)*(float)i/(float)(N_MELS+1u));double zsum=0,csum=0,fsum=0,bsum=0;float max_mel=0.0f;for(unsigned fr=0;fr<STFT_FRAMES;fr++){int start=(int)(fr*STFT_HOP)-(int)(STFT_N/2u);unsigned zc=0;float prev=sample_edge(pcm,start,dc,scale);for(unsigned i=1;i<STFT_N;i++){float cur=sample_edge(pcm,start+(int)i,dc,scale);if((cur>=0)!=(prev>=0))zc++;prev=cur;}zsum+=(double)zc/STFT_N;for(unsigned i=0;i<STFT_N;i++){g_fft[i].re=sample_norm(pcm,start+(int)i,dc,scale)*hann(i,STFT_N);g_fft[i].im=0.0f;}if(!zs_fft_radix2(g_fft,STFT_N))continue;double sum_mag=0,sum_fm=0,logp=0,sump=0;for(unsigned k=0;k<STFT_BINS;k++){float m=magc(g_fft[k]);float f=(float)k*(float)SR/(float)STFT_N;sum_mag+=m;sum_fm+=(double)f*m;float p=m*m+1e-10f;logp+=log((double)p);sump+=p;}float centroid=sum_mag>1e-20?(float)(sum_fm/sum_mag):0.0f;csum+=centroid;double bwv=0;if(sum_mag>1e-20){for(unsigned k=0;k<STFT_BINS;k++){float m=magc(g_fft[k]);float f=(float)k*(float)SR/(float)STFT_N;double d=(double)f-centroid;bwv+=(m/sum_mag)*d*d;}}bsum+=sqrt(fmax(0.0,bwv));double geo=exp(logp/STFT_BINS),arith=sump/STFT_BINS;fsum+=(arith>0)?geo/arith:0;for(unsigned m=0;m<N_MELS;m++){float left=mel_edges[m],center=mel_edges[m+1u],right=mel_edges[m+2u];float norm=2.0f/fmaxf(right-left,1e-12f);double e=0.0;unsigned k0=(unsigned)fmaxf(0.0f,floorf(left*STFT_N/(float)SR)),k2=(unsigned)fminf((float)(STFT_BINS-1u),ceilf(right*STFT_N/(float)SR));for(unsigned k=k0;k<=k2;k++){float f=(float)k*(float)SR/(float)STFT_N,w=0.0f;if(f>=left&&f<center)w=(f-left)/fmaxf(center-left,1e-12f);else if(f>=center&&f<=right)w=(right-f)/fmaxf(right-center,1e-12f);float mm=magc(g_fft[k]);e+=(double)(mm*mm)*w*norm;}g_mel[fr][m]=(float)e;if(g_mel[fr][m]>max_mel)max_mel=g_mel[fr][m];}}*zcr_frame_mean=(float)(zsum/STFT_FRAMES);*centroid_mean=(float)(csum/STFT_FRAMES);*flatness_mean=(float)(fsum/STFT_FRAMES);*bandwidth_mean=(float)(bsum/STFT_FRAMES);double sum[N_MFCC]={0},sumsq[N_MFCC]={0};float floor_db=10.0f*log10f(fmaxf(max_mel,1e-10f))-80.0f;for(unsigned fr=0;fr<STFT_FRAMES;fr++){float db[N_MELS];for(unsigned m=0;m<N_MELS;m++){float v=10.0f*log10f(fmaxf(g_mel[fr][m],1e-10f));if(v<floor_db)v=floor_db;db[m]=v;}for(unsigned k=0;k<N_MFCC;k++){double acc=0.0;for(unsigned m=0;m<N_MELS;m++)acc+=(double)db[m]*cos(M_PI*(double)k*((double)m+0.5)/(double)N_MELS);double coef=acc*((k==0)?sqrt(1.0/N_MELS):sqrt(2.0/N_MELS));sum[k]+=coef;sumsq[k]+=coef*coef;}}for(unsigned k=0;k<N_MFCC;k++){double mean=sum[k]/STFT_FRAMES,v=sumsq[k]/STFT_FRAMES-mean*mean;if(v<0)v=0;mfcc_mean[k]=(float)mean;mfcc_std[k]=(float)sqrt(v);}}
void zs_dsp_init(zs_dsp_ctx_t*ctx){if(ctx)memset(ctx,0,sizeof(*ctx));}bool zs_dsp_extract_1s(zs_dsp_ctx_t*ctx,const int16_t*pcm,size_t n,float out[ZS_FEATURE_COUNT]){if(!ctx||!pcm||!out||n!=NSAMP)return false;memset(out,0,ZS_FEATURE_COUNT*sizeof(float));float dc,scale,energy,rms,zcr_global;preprocess_stats(pcm,&dc,&scale,&energy,&rms,&zcr_global);ctx->last_dc=dc;ctx->last_peak=scale>0?1.0f/scale:0.0f;float max_mag;if(!global_spectrum(pcm,dc,scale,&max_mag))return false;float f0,f0var;estimate_f0_track(pcm,dc,scale,&f0,&f0var);if(f0<=0)f0=spectral_f0_fallback(max_mag);float hstep,hvar;unsigned hcount=detect_harmonics(f0,max_mag,&hstep,&hvar);float noise,high,rough;global_features(max_mag,&noise,&high,&rough);float zcr_frames,centroid,flatness,bandwidth,mmean[N_MFCC],mstd[N_MFCC];stft_and_mfcc(pcm,dc,scale,&zcr_frames,&centroid,&flatness,&bandwidth,mmean,mstd);float f0_stability=1.0f-f0var,spacing_stability=1.0f-hvar,hpresence=clamp01((float)hcount/24.0f);if(hpresence<0.15f)hpresence=0.15f;float hstab=f0>0?clamp01(0.45f*f0_stability+0.35f*spacing_stability+0.20f*hpresence):0.0f;out[0]=f0;out[1]=(float)hcount;out[2]=hstep;out[3]=hstab;out[4]=energy;out[5]=rms;out[6]=zcr_frames;out[7]=centroid;out[8]=flatness;out[9]=bandwidth;out[10]=noise;out[11]=high;out[12]=f0var;out[13]=hvar;out[14]=clamp01(f0var*4.0f);out[15]=rough;out[16]=clamp01(1.0f-f0var*5.0f);for(unsigned k=0;k<N_MFCC;k++){out[17u+k]=mmean[k];out[30u+k]=mstd[k];}ctx->windows_processed++;(void)zcr_global;return true;}bool zs_dsp_debug_global_magnitude(const int16_t*pcm,size_t n,float*out,size_t out_n){if(!pcm||n!=NSAMP||!out||out_n<GLOBAL_BINS)return false;float dc,scale,e,r,z;preprocess_stats(pcm,&dc,&scale,&e,&r,&z);float mx;if(!global_spectrum(pcm,dc,scale,&mx))return false;for(unsigned i=0;i<GLOBAL_BINS;i++)out[i]=g_mag[i];return true;}
