# Certificate CN is used as MQTT username (use_identity_as_username true).
user bridge
topic read zs/v1/evt/+/up
topic read zs/v1/evt/+/status
topic write zs/v1/evt/+/down
topic read zs/v1/evt/+/ack

user station01
topic write zs/v1/evt/1/up
topic write zs/v1/evt/1/status
topic read zs/v1/evt/1/down
topic write zs/v1/evt/1/ack

user station02
topic write zs/v1/evt/2/up
topic write zs/v1/evt/2/status
topic read zs/v1/evt/2/down
topic write zs/v1/evt/2/ack

user station03
topic write zs/v1/evt/3/up
topic write zs/v1/evt/3/status
topic read zs/v1/evt/3/down
topic write zs/v1/evt/3/ack

user station04
topic write zs/v1/evt/4/up
topic write zs/v1/evt/4/status
topic read zs/v1/evt/4/down
topic write zs/v1/evt/4/ack

user station05
topic write zs/v1/evt/5/up
topic write zs/v1/evt/5/status
topic read zs/v1/evt/5/down
topic write zs/v1/evt/5/ack

user station06
topic write zs/v1/evt/6/up
topic write zs/v1/evt/6/status
topic read zs/v1/evt/6/down
topic write zs/v1/evt/6/ack

user station07
topic write zs/v1/evt/7/up
topic write zs/v1/evt/7/status
topic read zs/v1/evt/7/down
topic write zs/v1/evt/7/ack

user station08
topic write zs/v1/evt/8/up
topic write zs/v1/evt/8/status
topic read zs/v1/evt/8/down
topic write zs/v1/evt/8/ack

user station09
topic write zs/v1/evt/9/up
topic write zs/v1/evt/9/status
topic read zs/v1/evt/9/down
topic write zs/v1/evt/9/ack

user station10
topic write zs/v1/evt/10/up
topic write zs/v1/evt/10/status
topic read zs/v1/evt/10/down
topic write zs/v1/evt/10/ack

user station11
topic write zs/v1/evt/11/up
topic write zs/v1/evt/11/status
topic read zs/v1/evt/11/down
topic write zs/v1/evt/11/ack

user station12
topic write zs/v1/evt/12/up
topic write zs/v1/evt/12/status
topic read zs/v1/evt/12/down
topic write zs/v1/evt/12/ack

user station13
topic write zs/v1/evt/13/up
topic write zs/v1/evt/13/status
topic read zs/v1/evt/13/down
topic write zs/v1/evt/13/ack

user station14
topic write zs/v1/evt/14/up
topic write zs/v1/evt/14/status
topic read zs/v1/evt/14/down
topic write zs/v1/evt/14/ack

user station15
topic write zs/v1/evt/15/up
topic write zs/v1/evt/15/status
topic read zs/v1/evt/15/down
topic write zs/v1/evt/15/ack

user station16
topic write zs/v1/evt/16/up
topic write zs/v1/evt/16/status
topic read zs/v1/evt/16/down
topic write zs/v1/evt/16/ack

user station17
topic write zs/v1/evt/17/up
topic write zs/v1/evt/17/status
topic read zs/v1/evt/17/down
topic write zs/v1/evt/17/ack

user station18
topic write zs/v1/evt/18/up
topic write zs/v1/evt/18/status
topic read zs/v1/evt/18/down
topic write zs/v1/evt/18/ack

user station19
topic write zs/v1/evt/19/up
topic write zs/v1/evt/19/status
topic read zs/v1/evt/19/down
topic write zs/v1/evt/19/ack

user station20
topic write zs/v1/evt/20/up
topic write zs/v1/evt/20/status
topic read zs/v1/evt/20/down
topic write zs/v1/evt/20/ack
