# Certificate CN is used as MQTT username (use_identity_as_username true).
user bridge
topic read zs/v1/evt/+/up
topic read zs/v1/evt/+/status
topic write zs/v1/evt/+/down

user station01
topic write zs/v1/evt/1/up
topic write zs/v1/evt/1/status
topic read zs/v1/evt/1/down

user station02
topic write zs/v1/evt/2/up
topic write zs/v1/evt/2/status
topic read zs/v1/evt/2/down

user station03
topic write zs/v1/evt/3/up
topic write zs/v1/evt/3/status
topic read zs/v1/evt/3/down

user station04
topic write zs/v1/evt/4/up
topic write zs/v1/evt/4/status
topic read zs/v1/evt/4/down
