#include "app_fw.h"
#include "app_config.h"
#include "app_fw_keys.h"          /* generated by CMake from ZS_FW_RELEASE_PUBLIC_KEYS */
#include "FreeRTOS.h"
#include "task.h"
#include "stm32u5xx_hal.h"
#include <string.h>

#define BANK_BYTES 0x100000u
#define PAGE_BYTES 0x2000u
#define IMAGE_BYTES (BANK_BYTES - PAGE_BYTES)           /* 1016 KiB: the linker keeps the image below the record page */
#define RUNNING_BASE 0x08000000u
#define OTHER_BASE 0x08100000u
#define RECORD_OFFSET IMAGE_BYTES
#define INSTALL_DELAY_MS 3000u

/* ---- .fw_info of this image (addendum F §1.2): the linker places it at image offset 0x400 ---- */
#define LE32(v) (uint8_t)((v) & 0xffu), (uint8_t)(((v) >> 8) & 0xffu), (uint8_t)(((v) >> 16) & 0xffu), (uint8_t)(((v) >> 24) & 0xffu)
__attribute__((section(".fw_info"), used)) const uint8_t app_fw_info[ZS_FW_INFO_BYTES] = {
  LE32(ZS_FW_INFO_MAGIC), (uint8_t)ZS_FW_INFO_FORMAT, 0u, (uint8_t)ZS_FW_TARGET_STM32_APP, 0u, LE32(APP_FW_VERSION_CODE)
};

static const zs_fw_release_key_t release_keys[APP_FW_RELEASE_KEY_COUNT ? APP_FW_RELEASE_KEY_COUNT : 1u] = APP_FW_RELEASE_KEYS_INIT;
static zs_fw_boot_record_t own_record;
static zs_fw_boot_action_t boot_action;
static bool install_pending, confirm_failed;
static uint32_t install_at_ms, install_version;
static uint32_t flash_errors;

/* The physical bank behind an address window: SWAP_BANK maps bank 2 at 0x08000000. */
static bool swapped(void) { return (FLASH->OPTR & FLASH_OPTR_SWAP_BANK) != 0u; }
static uint32_t other_physical_bank(void) { return swapped() ? FLASH_BANK_1 : FLASH_BANK_2; }

static bool erase_pages(uint32_t bank, uint32_t offset, uint32_t size) {
  FLASH_EraseInitTypeDef e;
  uint32_t page_error = 0u;
  HAL_StatusTypeDef st;
  if (offset % PAGE_BYTES || size % PAGE_BYTES || offset + size > BANK_BYTES || size == 0u) return false;
  e.TypeErase = FLASH_TYPEERASE_PAGES;
  e.Banks = bank;
  e.Page = offset / PAGE_BYTES;
  e.NbPages = size / PAGE_BYTES;
  (void)HAL_FLASH_Unlock();
  st = HAL_FLASHEx_Erase(&e, &page_error);
  (void)HAL_FLASH_Lock();
  (void)HAL_ICACHE_Invalidate();                    /* flash reads go through the ICACHE */
  if (st != HAL_OK) flash_errors++;
  return st == HAL_OK;
}

static bool program_quads(uint32_t address, const uint8_t *data, size_t size) {
  uint32_t quad[4];
  bool ok = true;
  if (address % 16u || size % 16u) return false;
  (void)HAL_FLASH_Unlock();
  for (size_t i = 0u; i < size && ok; i += 16u) {
    memcpy(quad, &data[i], sizeof(quad));
    ok = HAL_FLASH_Program(FLASH_TYPEPROGRAM_QUADWORD, address + (uint32_t)i, (uint32_t)quad) == HAL_OK;
  }
  (void)HAL_FLASH_Lock();
  (void)HAL_ICACHE_Invalidate();
  if (!ok) flash_errors++;
  return ok;
}

/* ---- image io: the image area of the other bank ---- */
static bool img_erase(void *ctx, uint32_t offset, uint32_t size) { (void)ctx; return erase_pages(other_physical_bank(), offset, size); }
static bool img_program(void *ctx, uint32_t offset, const uint8_t *data, size_t size) {
  (void)ctx;
  return offset + size <= IMAGE_BYTES && program_quads(OTHER_BASE + offset, data, size);
}
static bool img_read(void *ctx, uint32_t offset, uint8_t *data, size_t size) {
  (void)ctx;
  if (offset + size > BANK_BYTES) return false;
  memcpy(data, (const void *)(OTHER_BASE + offset), size);
  return true;
}
static const zs_fw_image_io_t image_io = {NULL, IMAGE_BYTES, PAGE_BYTES, RECORD_OFFSET, img_erase, img_program, img_read};

/* ---- boot record pages ---- */
static bool rec_read(void *ctx, uint32_t offset, uint8_t *data, size_t size) {
  const uint32_t base = (uint32_t)(uintptr_t)ctx;
  if (offset + size > PAGE_BYTES) return false;
  memcpy(data, (const void *)(base + RECORD_OFFSET + offset), size);
  return true;
}
static bool rec_program(void *ctx, uint32_t offset, const uint8_t slot[ZS_FW_BOOT_SLOT_BYTES]) {
  const uint32_t base = (uint32_t)(uintptr_t)ctx;
  return offset + ZS_FW_BOOT_SLOT_BYTES <= PAGE_BYTES && program_quads(base + RECORD_OFFSET + offset, slot, ZS_FW_BOOT_SLOT_BYTES);
}
static const zs_fw_boot_port_t own_port = {(void *)(uintptr_t)RUNNING_BASE, rec_read, rec_program};
static const zs_fw_boot_port_t other_port = {(void *)(uintptr_t)OTHER_BASE, rec_read, rec_program};

uint32_t app_fw_running_version(void) { return APP_FW_VERSION_CODE; }
bool app_fw_on_trial(void) { return own_record.armed && !own_record.confirmed; }

static void swap_and_reset(void) {
  FLASH_OBProgramInitTypeDef ob;
  memset(&ob, 0, sizeof(ob));
  ob.OptionType = OPTIONBYTE_USER;
  ob.USERType = OB_USER_SWAP_BANK;
  ob.USERConfig = swapped() ? OB_SWAP_BANK_DISABLE : OB_SWAP_BANK_ENABLE;
  (void)HAL_FLASH_Unlock();
  (void)HAL_FLASH_OB_Unlock();
  if (HAL_FLASHEx_OBProgram(&ob) == HAL_OK) (void)HAL_FLASH_OB_Launch();       /* reloads the option bytes: a reset */
  NVIC_SystemReset();                                                           /* not reached unless the OB write failed */
}

/* The IWDG with its longest timeout (LSI/256, reload 0xFFF ~ 32 s) before anything else can hang; the supervisor's
   app_watchdog_start() takes it over with the normal timeout. */
static void watchdog_early(void) {
  IWDG->KR = 0xCCCCu;
  IWDG->KR = 0x5555u;
  IWDG->PR = 6u;
  IWDG->RLR = 0xFFFu;
  for (unsigned i = 0u; i < 100000u && (IWDG->SR & (IWDG_SR_PVU | IWDG_SR_RVU)); i++) {}
  IWDG->KR = 0xAAAAu;
}

void app_fw_boot_guard(void) {
  boot_action = zs_fw_boot_guard(&own_port, &own_record);
  if (boot_action == ZS_FW_BOOT_ROLLBACK) swap_and_reset();
  if (boot_action == ZS_FW_BOOT_TRIAL) watchdog_early();
}

static bool fw_trial(void) { return app_fw_on_trial(); }
static void fw_install(uint32_t version) {
  install_version = version;
  install_at_ms = xTaskGetTickCount() + INSTALL_DELAY_MS;
  install_pending = true;
}
static const app_comms_fw_port_t port = {&image_io, &other_port, release_keys, APP_FW_RELEASE_KEY_COUNT, ZS_FW_TARGET_STM32_APP,
                                         app_fw_running_version, fw_trial, fw_install};
const app_comms_fw_port_t *app_fw_port(void) { return &port; }

void app_fw_confirm(bool selftest_ok) {
  if (!app_fw_on_trial() || !selftest_ok || confirm_failed) return;
  if (!zs_fw_boot_confirm(&own_port, &own_record)) confirm_failed = true;       /* the trial timeout decides then */
}

void app_fw_tick(uint32_t now_ms) {
  if (install_pending && (int32_t)(now_ms - install_at_ms) >= 0) {
    install_pending = false;
    vTaskDelay(pdMS_TO_TICKS(50));
    swap_and_reset();
  }
  if (app_fw_on_trial() && now_ms >= ZS_FW_BOOT_TRIAL_TIMEOUT_MS) NVIC_SystemReset();   /* the next attempt */
}

static uint32_t other_version(void) {
  uint8_t bytes[ZS_FW_INFO_BYTES];
  zs_fw_info_t info;
  return img_read(NULL, ZS_FW_INFO_OFFSET, bytes, sizeof(bytes)) && zs_fw_info_parse(bytes, &info) ? info.version : 0u;
}

void app_fw_fill_heartbeat(zs_detector_health_t *d) {
  zs_fw_boot_record_t other;
  uint8_t state = app_comms_fw_state();
  d->fw_version = APP_FW_VERSION_CODE;
  d->fw_other_version = other_version();
  if (state == 0u && app_fw_on_trial()) state = 3u;
  if (state == 0u && zs_fw_boot_read(&other_port, &other) && other.armed && !other.confirmed && other.rolled_back) state = 4u;
  d->fw_state = state;
}

void app_fw_status(void (*print)(const char *fmt, ...)) {
  print("firmware v%lu bank %u (%s) boot %s attempts %u%s | other bank v%lu | release keys %u | flash errors %lu%s\r\n",
        (unsigned long)APP_FW_VERSION_CODE, swapped() ? 2u : 1u, swapped() ? "swapped" : "not swapped", zs_fw_boot_action_name(boot_action),
        own_record.attempts, app_fw_on_trial() ? " (ON TRIAL)" : "", (unsigned long)other_version(), (unsigned)APP_FW_RELEASE_KEY_COUNT,
        (unsigned long)flash_errors, install_pending ? " | INSTALL PENDING" : "");
  (void)install_version;
}
