package ru.dioneya.commissioning.core.role

import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec

/**
 * B.9 engineer key of one station (ICD v0.2 §4): 32 bytes generated by the Muhoed registry
 * (`muhoed-pki engineer-key <serial>`), handed to the engineer as an audited export
 * `<serial>.engineer-key.json`.  It never appears on the label and never leaves the phone
 * once imported (see the Android `EngineerKeyStore`).  Pure Kotlin.
 */
class EngineerKey(val serial: String, val key: ByteArray) {
    init {
        require(serial.isNotBlank()) { "serial required" }
        require(key.size == KEY_BYTES) { "engineer key must be $KEY_BYTES bytes" }
    }

    /**
     * `tag16 = HMAC-SHA256(engineer_key, "DIO-ROLE-V1" ‖ serial_ascii ‖ nonce16)[0..15]`.
     * Vector: key a0..bf, serial DIO-EVT-012, nonce 00..0f → e3f70cf47e0a591490b501d6ba31be7b.
     */
    fun roleTag(nonce: ByteArray): ByteArray {
        require(nonce.size == NONCE_BYTES) { "nonce must be $NONCE_BYTES bytes" }
        val mac = Mac.getInstance("HmacSHA256")
        mac.init(SecretKeySpec(key, "HmacSHA256"))
        mac.update(CONTEXT.toByteArray(Charsets.US_ASCII))
        mac.update(serial.toByteArray(Charsets.US_ASCII))
        mac.update(nonce)
        return mac.doFinal().copyOf(TAG_BYTES)
    }

    companion object {
        const val CONTEXT = "DIO-ROLE-V1"
        const val KEY_BYTES = 32
        const val NONCE_BYTES = 16
        const val TAG_BYTES = 16

        /**
         * Parses the registry export `{"serial": …, "engineer_key_hex": …, "context": "DIO-ROLE-V1"}`.
         * A minimal reader: the file is small, flat and produced by our own tool.  Returns null
         * when a field is missing, the key is not 64 hex digits or the context is foreign.
         */
        fun fromExportJson(text: String): EngineerKey? {
            val serial = jsonString(text, "serial") ?: return null
            val hex = jsonString(text, "engineer_key_hex") ?: return null
            val context = jsonString(text, "context") ?: CONTEXT
            if (context != CONTEXT) return null
            val key = hexToBytes(hex) ?: return null
            if (key.size != KEY_BYTES) return null
            return try { EngineerKey(serial, key) } catch (_: IllegalArgumentException) { null }
        }

        fun hexToBytes(hex: String): ByteArray? {
            val h = hex.trim()
            if (h.length % 2 != 0 || h.isEmpty()) return null
            val out = ByteArray(h.length / 2)
            for (i in out.indices) {
                val hi = Character.digit(h[2 * i], 16); val lo = Character.digit(h[2 * i + 1], 16)
                if (hi < 0 || lo < 0) return null
                out[i] = ((hi shl 4) or lo).toByte()
            }
            return out
        }

        fun bytesToHex(b: ByteArray): String = b.joinToString("") { "%02x".format(it) }

        private fun jsonString(text: String, key: String): String? {
            val m = Regex("\"" + Regex.escape(key) + "\"\\s*:\\s*\"([^\"\\\\]*)\"").find(text) ?: return null
            return m.groupValues[1]
        }
    }
}
