/* Generated by tools/generate_evt_pre_20_target_contract.py; do not edit. */
#ifndef EVT_PRE_20_CLOCK_POLICY_H
#define EVT_PRE_20_CLOCK_POLICY_H

#include <stdint.h>

#define EVT_PRE_20_CLOCK_POLICY_ID "REV_A_INTERNAL_HSI_MSI_PLL_NO_HSE"
#define EVT_PRE_20_EXTERNAL_HSE_ALLOWED 0
#define EVT_PRE_20_LOW_SPEED_REFERENCE "SiT1552AI-JE-DCC-32.768D"
#define EVT_PRE_20_LOW_SPEED_REFERENCE_HZ UINT32_C(32768)
#define EVT_PRE_20_RUNTIME_CLOCK_FREQUENCIES_RELEASED 0
#define EVT_PRE_20_RUNTIME_CLOCK_PROFILE_COUNT 5u

typedef enum {
  EVT_PRE_20_CLOCK_PROFILE_S0_SLEEP = 0,
  EVT_PRE_20_CLOCK_PROFILE_S1_LISTEN,
  EVT_PRE_20_CLOCK_PROFILE_S2_DSP,
  EVT_PRE_20_CLOCK_PROFILE_S3_COMMS,
  EVT_PRE_20_CLOCK_PROFILE_S4_SERVICE
} evt_pre_20_clock_profile_t;

_Static_assert(EVT_PRE_20_EXTERNAL_HSE_ALLOWED == 0,
               "EVT-PRE-20 Rev.A must not depend on external HSE");
_Static_assert(EVT_PRE_20_LOW_SPEED_REFERENCE_HZ == UINT32_C(32768),
               "EVT-PRE-20 low-speed reference mismatch");

#endif
