/* Generated by tools/generate_evt_pre_20_target_contract.py; do not edit. */
#ifndef EVT_PRE_20_BOARD_PINS_H
#define EVT_PRE_20_BOARD_PINS_H

#include <stddef.h>
#include <stdint.h>

#define EVT_PRE_20_TARGET_ID "dioneya_evt_pre_20_rev_a"
#define EVT_PRE_20_MCU_MPN "STM32U585VIT6Q"
#define EVT_PRE_20_MCU_PACKAGE "LQFP100_14x14"
#define EVT_PRE_20_PIN_DATABASE "STM32U585VITxQ"
#define EVT_PRE_20_PIN_ASSIGNMENT_COUNT 67u
#define EVT_PRE_20_AF_GPIO (-1)
#define EVT_PRE_20_AF_RCC (-2)
#define EVT_PRE_20_AF_SYS (-3)

typedef enum {
  EVT_PRE_20_DIRECTION_IN = 0,
  EVT_PRE_20_DIRECTION_OUT,
  EVT_PRE_20_DIRECTION_BIDIR,
  EVT_PRE_20_DIRECTION_OUT_OD,
  EVT_PRE_20_DIRECTION_BIDIR_OD
} evt_pre_20_pin_direction_t;

typedef struct {
  const char *net;
  const char *function;
  char gpio_port;
  uint8_t gpio_pin;
  uint8_t lqfp100_pin;
  const char *cubemx_signal;
  int8_t alternate_function;
  evt_pre_20_pin_direction_t direction;
} evt_pre_20_pin_contract_t;

static const evt_pre_20_pin_contract_t evt_pre_20_pin_contract[] = {
  {"PDM_CLK", "Microphone common PDM clock", 'E', 9u, 37u, "MDF1_CCK0", 6, EVT_PRE_20_DIRECTION_OUT},
  {"PDM_DATA1", "Microphone PDM data channel 1", 'B', 1u, 33u, "MDF1_SDI0", 6, EVT_PRE_20_DIRECTION_IN},
  {"PDM_DATA2", "Microphone PDM data channel 2", 'D', 6u, 87u, "MDF1_SDI1", 6, EVT_PRE_20_DIRECTION_IN},
  {"PDM_DATA3", "Microphone PDM data channel 3", 'E', 7u, 35u, "MDF1_SDI2", 6, EVT_PRE_20_DIRECTION_IN},
  {"PDM_DATA4", "Microphone PDM data channel 4", 'E', 4u, 3u, "MDF1_SDI3", 6, EVT_PRE_20_DIRECTION_IN},
  {"MIC_WAKE", "Aggregated T5838 Acoustic Activity Detect wake", 'A', 8u, 67u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"NOR_CLK", "QSPI NOR clock", 'E', 10u, 38u, "OCTOSPIM_P1_CLK", 10, EVT_PRE_20_DIRECTION_OUT},
  {"NOR_NCS", "QSPI NOR chip select", 'E', 11u, 39u, "OCTOSPIM_P1_NCS", 10, EVT_PRE_20_DIRECTION_OUT},
  {"NOR_IO0", "QSPI NOR IO0", 'E', 12u, 40u, "OCTOSPIM_P1_IO0", 10, EVT_PRE_20_DIRECTION_BIDIR},
  {"NOR_IO1", "QSPI NOR IO1", 'E', 13u, 41u, "OCTOSPIM_P1_IO1", 10, EVT_PRE_20_DIRECTION_BIDIR},
  {"NOR_IO2", "QSPI NOR IO2", 'E', 14u, 42u, "OCTOSPIM_P1_IO2", 10, EVT_PRE_20_DIRECTION_BIDIR},
  {"NOR_IO3", "QSPI NOR IO3", 'E', 15u, 43u, "OCTOSPIM_P1_IO3", 10, EVT_PRE_20_DIRECTION_BIDIR},
  {"SD_D0", "microSD data 0", 'C', 8u, 65u, "SDMMC1_D0", 12, EVT_PRE_20_DIRECTION_BIDIR},
  {"SD_D1", "microSD data 1", 'C', 9u, 66u, "SDMMC1_D1", 12, EVT_PRE_20_DIRECTION_BIDIR},
  {"SD_D2", "microSD data 2", 'C', 10u, 78u, "SDMMC1_D2", 12, EVT_PRE_20_DIRECTION_BIDIR},
  {"SD_D3", "microSD data 3", 'C', 11u, 79u, "SDMMC1_D3", 12, EVT_PRE_20_DIRECTION_BIDIR},
  {"SD_CK", "microSD clock", 'C', 12u, 80u, "SDMMC1_CK", 12, EVT_PRE_20_DIRECTION_OUT},
  {"SD_CMD", "microSD command", 'D', 2u, 83u, "SDMMC1_CMD", 12, EVT_PRE_20_DIRECTION_BIDIR},
  {"SD_DET", "microSD card detect", 'C', 13u, 7u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"GNSS_TX", "GNSS UART transmit", 'A', 2u, 24u, "USART2_TX", 7, EVT_PRE_20_DIRECTION_OUT},
  {"GNSS_RX", "GNSS UART receive", 'A', 3u, 25u, "USART2_RX", 7, EVT_PRE_20_DIRECTION_IN},
  {"GNSS_PPS", "GNSS TIMEPULSE timestamp", 'A', 0u, 22u, "TIM2_CH1", 1, EVT_PRE_20_DIRECTION_IN},
  {"LORA_NSS", "LoRa SPI chip select", 'A', 4u, 28u, "SPI1_NSS", 5, EVT_PRE_20_DIRECTION_OUT},
  {"LORA_SCK", "LoRa SPI clock", 'A', 5u, 29u, "SPI1_SCK", 5, EVT_PRE_20_DIRECTION_OUT},
  {"LORA_MISO", "LoRa SPI MISO", 'A', 6u, 30u, "SPI1_MISO", 5, EVT_PRE_20_DIRECTION_IN},
  {"LORA_MOSI", "LoRa SPI MOSI", 'A', 7u, 31u, "SPI1_MOSI", 5, EVT_PRE_20_DIRECTION_OUT},
  {"LORA_DIO1", "LoRa interrupt", 'C', 2u, 17u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"LORA_TXEN", "LoRa RF switch transmit enable", 'B', 15u, 54u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"LORA_RXEN", "LoRa RF switch receive enable", 'D', 8u, 55u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"LORA_BUSY", "LoRa busy", 'D', 9u, 56u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"LORA_RESET_N", "LoRa reset", 'D', 10u, 57u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"CELL_TX", "Cellular main UART transmit", 'B', 6u, 92u, "USART1_TX", 7, EVT_PRE_20_DIRECTION_OUT},
  {"CELL_RX", "Cellular main UART receive", 'B', 7u, 93u, "USART1_RX", 7, EVT_PRE_20_DIRECTION_IN},
  {"CELL_PWRKEY_CMD", "Cellular PWRKEY control", 'D', 11u, 58u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"CELL_RESET_N_CMD", "Cellular reset control", 'D', 12u, 59u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"CELL_STATUS", "Cellular status input", 'D', 13u, 60u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"CELL_DTR", "Cellular DTR control", 'D', 14u, 61u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"CELL_RI", "Cellular ring indicator", 'D', 15u, 62u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"SIM_MUX_SEL", "Dual-SIM mux select", 'E', 0u, 97u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"SIM_MUX_EN", "Dual-SIM mux enable", 'E', 2u, 1u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"SIM1_DET", "SIM1 card detect", 'E', 3u, 2u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"SIM2_DET", "SIM2 card detect", 'E', 5u, 4u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"BLE_TX", "BLE service UART transmit", 'B', 10u, 44u, "USART3_TX", 7, EVT_PRE_20_DIRECTION_OUT},
  {"BLE_RX", "BLE service UART receive", 'B', 11u, 45u, "USART3_RX", 7, EVT_PRE_20_DIRECTION_IN},
  {"BLE_EN", "BLE module enable/reset request", 'E', 6u, 5u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"BLE_DFU_REQ", "BLE application DFU/recovery request", 'B', 2u, 34u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT_OD},
  {"I2C2_SCL", "Power and sensor I2C clock", 'B', 13u, 52u, "I2C2_SCL", 4, EVT_PRE_20_DIRECTION_BIDIR_OD},
  {"I2C2_SDA", "Power and sensor I2C data", 'B', 14u, 53u, "I2C2_SDA", 4, EVT_PRE_20_DIRECTION_BIDIR_OD},
  {"PWR_GOOD", "Power interface good input", 'D', 0u, 81u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"PWR_FAULT", "Power interface fault input", 'D', 1u, 82u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"EN_MODEM", "Modem power enable", 'D', 4u, 85u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"EN_AUX", "Auxiliary RF/microphone enable", 'D', 5u, 86u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
  {"ACCEL_INT", "Accelerometer interrupt", 'C', 6u, 63u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"TAMPER_IN", "Enclosure tamper input", 'C', 7u, 64u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"TEST_UART_RX", "Production diagnostic UART receive", 'C', 0u, 15u, "LPUART1_RX", 8, EVT_PRE_20_DIRECTION_IN},
  {"TEST_UART_TX", "Production diagnostic UART transmit", 'C', 1u, 16u, "LPUART1_TX", 8, EVT_PRE_20_DIRECTION_OUT},
  {"USB_VBUS", "USB service VBUS sense", 'A', 9u, 68u, "USB_OTG_FS_VBUS", 10, EVT_PRE_20_DIRECTION_IN},
  {"USB_DM", "USB service D-", 'A', 11u, 70u, "USB_OTG_FS_DM", 10, EVT_PRE_20_DIRECTION_BIDIR},
  {"USB_DP", "USB service D+", 'A', 12u, 71u, "USB_OTG_FS_DP", 10, EVT_PRE_20_DIRECTION_BIDIR},
  {"SWDIO", "SWD data", 'A', 13u, 72u, "DEBUG_JTMS-SWDIO", -3, EVT_PRE_20_DIRECTION_BIDIR},
  {"SWCLK", "SWD clock", 'A', 14u, 76u, "DEBUG_JTCK-SWCLK", -3, EVT_PRE_20_DIRECTION_IN},
  {"BOOT0", "MCU boot strap", 'H', 3u, 94u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"REV_STRAP0", "Hardware revision strap 0", 'B', 8u, 95u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"REV_STRAP1", "Hardware revision strap 1", 'B', 9u, 96u, "GPIO", -1, EVT_PRE_20_DIRECTION_IN},
  {"LSE_IN", "32.768 kHz clock input", 'C', 14u, 8u, "RCC_OSC32_IN", -2, EVT_PRE_20_DIRECTION_IN},
  {"LSE_OUT", "32.768 kHz clock output/reserved", 'C', 15u, 9u, "RCC_OSC32_OUT", -2, EVT_PRE_20_DIRECTION_OUT},
  {"AAD_CFG", "T5838 shared THSEL one-wire configuration", 'A', 15u, 77u, "GPIO", -1, EVT_PRE_20_DIRECTION_OUT},
};

_Static_assert(
    sizeof(evt_pre_20_pin_contract) / sizeof(evt_pre_20_pin_contract[0]) ==
        EVT_PRE_20_PIN_ASSIGNMENT_COUNT,
    "EVT-PRE-20 pin contract count mismatch");

#endif
