#!/usr/bin/env python3
"""Generate EVT-PRE-20 PCB-MIC Rev.A native KiCad board candidate.

The board is created by KiCad's pcbnew API. EasyEDA/LCSC CAD is used only as a
secondary geometry reference after inspection. The production T5838 central GND land
is rebuilt from TDK DS-000383 as one continuous annular pad instead of the four
incorrectly disconnected copper quadrants present in the secondary import.

Rev.A electrical layout strategy:
- 2 layers;
- PDM/AAD signals on F.Cu;
- continuous B.Cu GND reference zone;
- 1V8 crossing confined to a short B.Cu corridor on the right side;
- T5838 rotated to remove PDM_DATA/PDM_CLK crossings;
- acoustic NPTH = 0.8 mm, inside TDK recommended 0.5..1.0 mm range;
- manufacturer pad/stencil dimensions retained where directly available.

The 24 x 22 mm outline and fastening scheme remain provisional until microphone mount
mechanics freezes them. DRC PASS alone must never mark this board FOR_MANUFACTURE.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import pcbnew


def v(x: float, y: float):
    return pcbnew.VECTOR2I(pcbnew.FromMM(x), pcbnew.FromMM(y))


def mm(value: float) -> int:
    return pcbnew.FromMM(value)


def load_one(root: Path):
    mods = sorted(root.rglob("*.kicad_mod"))
    if len(mods) != 1:
        raise RuntimeError(f"expected one footprint below {root}, found {mods}")
    fp = pcbnew.FootprintLoad(str(mods[0].parent), mods[0].stem)
    if fp is None:
        raise RuntimeError(f"could not load {mods[0]}")
    return fp


def add_net(board, name: str):
    net = pcbnew.NETINFO_ITEM(board, name)
    board.Add(net)
    return net


def pads_by_number(fp, number: str):
    return [p for p in fp.Pads() if str(p.GetNumber()) == str(number)]


def one_pad(fp, number: str):
    pads = pads_by_number(fp, number)
    if len(pads) != 1:
        raise RuntimeError(f"{fp.GetReference()} pad {number}: expected one, got {len(pads)}")
    return pads[0]


def assign(fp, number: str, net) -> None:
    pads = pads_by_number(fp, number)
    if not pads:
        raise RuntimeError(f"{fp.GetReference()} missing pad {number}")
    for p in pads:
        p.SetNet(net)


def pos(pad):
    p = pad.GetPosition()
    return (pcbnew.ToMM(p.x), pcbnew.ToMM(p.y))


def set_rel(item, x: float, y: float) -> None:
    p = v(x, y)
    if hasattr(item, "SetFPRelativePosition"):
        item.SetFPRelativePosition(p)
    else:
        item.SetPos0(p)
        item.SetPosition(p)


def layer_set(*layers):
    ls = pcbnew.LSET()
    for layer in layers:
        ls.AddLayer(layer)
    return ls


def add_track(board, net, points: list[tuple[float, float]], width: float = 0.25, layer=pcbnew.F_Cu):
    for a, b in zip(points, points[1:]):
        t = pcbnew.PCB_TRACK(board)
        t.SetStart(v(*a))
        t.SetEnd(v(*b))
        t.SetWidth(mm(width))
        t.SetLayer(layer)
        t.SetNet(net)
        board.Add(t)


def add_via(board, net, xy: tuple[float, float], diameter: float = 0.65, drill: float = 0.30):
    via = pcbnew.PCB_VIA(board)
    via.SetPosition(v(*xy))
    via.SetWidth(mm(diameter))
    via.SetDrill(mm(drill))
    via.SetViaType(pcbnew.VIATYPE_THROUGH)
    via.SetNet(net)
    board.Add(via)
    return via


def add_edge(board, a, b):
    s = pcbnew.PCB_SHAPE(board)
    s.SetShape(pcbnew.SHAPE_T_SEGMENT)
    s.SetStart(v(*a))
    s.SetEnd(v(*b))
    s.SetLayer(pcbnew.Edge_Cuts)
    s.SetWidth(mm(0.15))
    board.Add(s)


def hide_fields(fp) -> None:
    # Assembly references are carried on Fab/assembly output; autogenerated secondary
    # reference text is hidden from F.Silk to prevent meaningless DRC noise/collisions.
    try:
        fp.Reference().SetVisible(False)
        fp.Value().SetVisible(False)
    except Exception:
        pass


def rebuild_t5838_manufacturer_land(mic) -> None:
    """Replace secondary-CAD center land with TDK manufacturer-derived geometry."""
    # Remove four disconnected EasyEDA custom-pad quadrants and its plated 0.38 mm hole.
    for pad in list(mic.Pads()):
        if str(pad.GetNumber()) in ("3", ""):
            mic.RemoveNative(pad)

    # Figure 36 copper land: outer phi1.625 / inner phi1.025 => centerline radius
    # 0.6625 mm with 0.300 mm stroke. One custom pad preserves electrical continuity.
    ring = pcbnew.PAD(mic)
    ring.SetNumber("3")
    ring.SetShape(pcbnew.PAD_SHAPE_CUSTOM)
    ring.SetAttribute(pcbnew.PAD_ATTRIB_SMD)
    ring.SetLayerSet(layer_set(pcbnew.F_Cu, pcbnew.F_Mask))
    ring.SetSize(v(0.01, 0.01))
    set_rel(ring, -0.65, 0.0)
    try:
        ring.SetAnchorPadShape(pcbnew.F_Cu, pcbnew.PAD_SHAPE_CIRCLE)
    except TypeError:
        ring.SetAnchorPadShape(pcbnew.PAD_SHAPE_CIRCLE)
    ring.AddPrimitive(v(0.0, 0.0), mm(0.6625), mm(0.300))
    mic.Add(ring)

    # Suggested stencil has a smaller central opening than copper. A continuous
    # paste-ring aperture is used as the electrical candidate; quadrant/gap stencil
    # optimization remains a Review-B/assembler DFM item before release.
    paste = pcbnew.PAD(mic)
    paste.SetNumber("")
    paste.SetShape(pcbnew.PAD_SHAPE_CUSTOM)
    paste.SetAttribute(pcbnew.PAD_ATTRIB_SMD)
    paste.SetLayerSet(paste.ApertureMask())
    paste.SetSize(v(0.01, 0.01))
    set_rel(paste, -0.65, 0.0)
    try:
        paste.SetAnchorPadShape(pcbnew.F_Paste, pcbnew.PAD_SHAPE_CIRCLE)
    except TypeError:
        paste.SetAnchorPadShape(pcbnew.PAD_SHAPE_CIRCLE)
    # Figure 37 phi1.625 / phi1.125 => centerline 0.6875, width 0.250 mm.
    paste.AddPrimitive(v(0.0, 0.0), mm(0.6875), mm(0.250))
    mic.Add(paste)

    # Separate acoustic NPTH. Copper inner diameter is 1.025 mm, leaving a deliberate
    # copper-to-drill radial gap around the 0.8 mm unplated acoustic opening.
    hole = pcbnew.PAD(mic)
    hole.SetNumber("")
    hole.SetShape(pcbnew.PAD_SHAPE_CIRCLE)
    hole.SetAttribute(pcbnew.PAD_ATTRIB_NPTH)
    hole.SetLayerSet(hole.UnplatedHoleMask())
    hole.SetSize(v(0.8, 0.8))
    hole.SetDrillSize(v(0.8, 0.8))
    set_rel(hole, -0.65, 0.0)
    mic.Add(hole)

    # Figure 37 reduces stencil openings relative to copper on signal/power lands.
    for number in ("1", "2", "6", "7"):
        one_pad(mic, number).SetLocalSolderPasteMargin(-mm(0.05))
    for number in ("4", "5"):
        one_pad(mic, number).SetLocalSolderPasteMargin(-mm(0.015))


def add_ground_zone(board, gnd_net, width: float, height: float) -> None:
    zone = pcbnew.ZONE(board)
    zone.SetLayer(pcbnew.B_Cu)
    zone.SetNetCode(gnd_net.GetNetCode())
    zone.SetZoneName("PCB_MIC_BCU_GND_REFERENCE")
    inset = 0.65
    polygon = pcbnew.SHAPE_LINE_CHAIN()
    for x, y in (
        (inset, inset),
        (width - inset, inset),
        (width - inset, height - inset),
        (inset, height - inset),
    ):
        polygon.Append(v(x, y))
    polygon.SetClosed(True)
    zone.AddPolygon(polygon)
    board.Add(zone)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--t5838-root", type=Path, required=True)
    ap.add_argument("--molex-root", type=Path, required=True)
    ap.add_argument("--reference-report", type=Path, required=True)
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()

    report = json.loads(args.reference_report.read_text(encoding="utf-8"))
    if not report["t5838"]["t5838_check"]["manufacturer_geometry_partial_pass"]:
        raise RuntimeError("T5838 secondary footprint failed manufacturer geometry check")
    if not report["molex_5040500691"]["molex_check"]["six_circuit_partial_pass"]:
        raise RuntimeError("Molex secondary footprint failed six-circuit check")

    board = pcbnew.BOARD()
    ds = board.GetDesignSettings()
    ds.SetCopperLayerCount(2)

    nets = {n: add_net(board, n) for n in (
        "1V8_MIC", "GND", "PDM_CLK", "PDM_DATA", "MIC_WAKE", "AAD_CFG", "PDM_DATA_MIC"
    )}

    board_w, board_h = 24.0, 22.0

    mic = load_one(args.t5838_root)
    rebuild_t5838_manufacturer_land(mic)
    mic.SetReference("MK1")
    mic.SetValue("T5838")
    mic.SetOrientationDegrees(270.0)
    mic.SetPosition(v(12.0, 16.0))
    hide_fields(mic)
    board.Add(mic)

    # Datasheet pin mapping: 1 DATA, 2 SELECT, 3 GND, 4 WAKE, 5 THSEL, 6 CLK, 7 VDD.
    assign(mic, "1", nets["PDM_DATA_MIC"])
    assign(mic, "2", nets["GND"])
    assign(mic, "3", nets["GND"])
    assign(mic, "4", nets["MIC_WAKE"])
    assign(mic, "5", nets["AAD_CFG"])
    assign(mic, "6", nets["PDM_CLK"])
    assign(mic, "7", nets["1V8_MIC"])

    j1 = load_one(args.molex_root)
    j1.SetReference("J1")
    j1.SetValue("5040500691")
    j1.SetOrientationDegrees(180.0)
    j1.SetPosition(v(12.0, 5.0))
    hide_fields(j1)
    board.Add(j1)
    for number, netname in {
        "1": "1V8_MIC", "2": "GND", "3": "PDM_CLK", "4": "PDM_DATA", "5": "MIC_WAKE", "6": "AAD_CFG"
    }.items():
        assign(j1, number, nets[netname])

    caplib = Path("/usr/share/kicad/footprints/Capacitor_SMD.pretty")
    c1 = pcbnew.FootprintLoad(str(caplib), "C_0402_1005Metric")
    if c1 is None:
        raise RuntimeError("KiCad C_0402_1005Metric footprint unavailable")
    c1.SetReference("C1")
    c1.SetValue("100nF X7R")
    c1.SetPosition(v(14.1, 13.25))
    hide_fields(c1)
    board.Add(c1)
    assign(c1, "1", nets["1V8_MIC"])
    assign(c1, "2", nets["GND"])

    rlib = Path("/usr/share/kicad/footprints/Resistor_SMD.pretty")
    r1 = pcbnew.FootprintLoad(str(rlib), "R_0402_1005Metric")
    if r1 is None:
        raise RuntimeError("KiCad R_0402_1005Metric footprint unavailable")
    r1.SetReference("R1")
    r1.SetValue("0R EVT_SI_TUNE")
    r1.SetOrientationDegrees(270.0)
    r1.SetPosition(v(11.25, 10.55))
    hide_fields(r1)
    board.Add(r1)
    assign(r1, "1", nets["PDM_DATA"])
    assign(r1, "2", nets["PDM_DATA_MIC"])

    for a, b in [
        ((0, 0), (board_w, 0)),
        ((board_w, 0), (board_w, board_h)),
        ((board_w, board_h), (0, board_h)),
        ((0, board_h), (0, 0)),
    ]:
        add_edge(board, a, b)

    jp = {str(i): pos(one_pad(j1, str(i))) for i in range(1, 7)}
    mp = {str(i): pos(one_pad(mic, str(i))) for i in (1, 2, 4, 5, 6, 7)}
    rp1, rp2 = pos(one_pad(r1, "1")), pos(one_pad(r1, "2"))
    cp1, cp2 = pos(one_pad(c1, "1")), pos(one_pad(c1, "2"))

    # PDM DATA: connector -> R1 -> microphone. The 0R value is an EVT baseline;
    # 22/33/47R are evaluated by EVT-AUD-SI-01 before BOM freeze.
    add_track(board, nets["PDM_DATA"], [jp["4"], rp1], width=0.22)
    add_track(board, nets["PDM_DATA_MIC"], [rp2, (rp2[0], 13.45), mp["1"]], width=0.22)

    # PDM clock uses a dedicated right-side corridor and approaches pin 6 laterally.
    clock_lane_x = 17.2
    add_track(board, nets["PDM_CLK"], [
        jp["3"],
        (14.0, 9.0),
        (clock_lane_x, 9.0),
        (clock_lane_x, mp["6"][1]),
        mp["6"],
    ], width=0.22)

    # WAKE stays left of the acoustic land; AAD_CFG goes below the microphone and
    # returns to THSEL from the right, keeping both lines away from PDM clock/data.
    add_track(board, nets["MIC_WAKE"], [jp["5"], (jp["5"][0], mp["4"][1]), mp["4"]], width=0.20)
    add_track(board, nets["AAD_CFG"], [
        jp["6"],
        (jp["6"][0], 20.25),
        (mp["5"][0], 20.25),
        mp["5"],
    ], width=0.20)

    # 1V8 crosses the board on B.Cu at the far right so the signal side remains
    # planar. Local F.Cu fanout covers connector/via and via/C1/VDD only.
    vdd_in = (18.6, 7.7)
    vdd_local = (13.35, 12.15)
    add_via(board, nets["1V8_MIC"], vdd_in)
    add_via(board, nets["1V8_MIC"], vdd_local)
    add_track(board, nets["1V8_MIC"], [jp["1"], vdd_in], width=0.35)
    add_track(board, nets["1V8_MIC"], [
        vdd_in,
        (20.0, 8.5),
        (20.0, 11.6),
        vdd_local,
    ], width=0.40, layer=pcbnew.B_Cu)
    add_track(board, nets["1V8_MIC"], [vdd_local, cp1, mp["7"]], width=0.30)

    # GND drops immediately to the B.Cu reference at connector, bypass capacitor and
    # microphone annulus. SELECT is locally strapped to the annular GND land.
    gnd_j = (jp["2"][0], 8.65)
    gnd_c = (15.25, cp2[1])
    # T5838 annulus center after 270-degree rotation is +0.65 mm in Y from footprint center.
    ring_center = (12.0, 16.65)
    gnd_m = (15.0, ring_center[1])
    add_via(board, nets["GND"], gnd_j)
    add_via(board, nets["GND"], gnd_c)
    add_via(board, nets["GND"], gnd_m)
    add_track(board, nets["GND"], [jp["2"], gnd_j], width=0.35)
    add_track(board, nets["GND"], [cp2, gnd_c], width=0.30)
    # Start the annulus track inside its copper ring, not at the acoustic-hole center.
    add_track(board, nets["GND"], [(12.70, ring_center[1]), gnd_m], width=0.30)
    # SELECT -> annulus at a point inside the copper ring on the upper-left quadrant.
    add_track(board, nets["GND"], [mp["2"], (11.70, 16.05)], width=0.16)

    add_ground_zone(board, nets["GND"], board_w, board_h)
    pcbnew.ZONE_FILLER(board).Fill(board.Zones())

    txt = pcbnew.PCB_TEXT(board)
    txt.SetText("PCB-MIC Rev.A ELECTRICAL CANDIDATE - 24x22 OUTLINE/FASTENING PROVISIONAL")
    txt.SetPosition(v(12.0, 21.2))
    txt.SetLayer(pcbnew.F_Fab)
    txt.SetTextHeight(mm(0.7))
    txt.SetTextWidth(mm(0.7))
    txt.SetTextThickness(mm(0.11))
    board.Add(txt)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    pcbnew.SaveBoard(str(args.output), board)
    print(f"saved {args.output}")
    print("tracks/vias", len(board.GetTracks()), "footprints", len(list(board.GetFootprints())), "zones", len(list(board.Zones())))
    print("T5838 land: manufacturer annular GND phi1.625/phi1.025; acoustic NPTH 0.8 mm")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
