#!/usr/bin/env python3
"""Generate the deterministic server-to-firmware signed command test vector."""

from __future__ import annotations

import argparse
import cbor2
from pathlib import Path
import sys

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey


ROOT = Path(__file__).resolve().parents[1]
SERVER_ROOT = ROOT / "server"
OUTPUT = ROOT / "firmware" / "generated" / "zs_command_vector.h"
sys.path.insert(0, str(SERVER_ROOT))

from station.command_codec import (  # noqa: E402
    CommandAck,
    CommandSigner,
    encode_command_ack,
    encode_signed_command,
)
from station.schemas import StationCommand  # noqa: E402


# Deterministic repository material for an interoperability test only. This key
# is public repository data and must never be accepted by production firmware.
TEST_PRIVATE_SEED = bytes(range(1, 33))
COMMAND_ID = "12345678-1234-5678-1234-567812345678"


def c_array(name: str, value: bytes) -> str:
    lines = []
    for offset in range(0, len(value), 12):
        chunk = ", ".join(f"0x{byte:02x}u" for byte in value[offset : offset + 12])
        lines.append(f"    {chunk},")
    return (
        f"static const uint8_t {name}[{len(value)}] = {{\n"
        + "\n".join(lines)
        + "\n};"
    )


def render() -> str:
    private_key = Ed25519PrivateKey.from_private_bytes(TEST_PRIVATE_SEED)
    signer = CommandSigner(private_key)
    command = StationCommand(
        command_id=COMMAND_ID,
        station_id=17,
        command="CMD_REQUEST_AUDIO",
        payload={"event_id": 42, "segment": "both"},
        created_time_us=1_000_000,
        expires_time_us=2_000_000,
    )
    payload = encode_signed_command(command, signer)
    envelope = cbor2.loads(payload)
    signed_cbor = cbor2.dumps({key: envelope[key] for key in range(9)}, canonical=True)
    signature = envelope[9]
    public_key = private_key.public_key().public_bytes(
        serialization.Encoding.Raw,
        serialization.PublicFormat.Raw,
    )
    private_key.public_key().verify(signature, signed_cbor)
    assert signer.key_id == envelope[8]
    assert len(payload) <= 2048
    ack = encode_command_ack(
        CommandAck(
            station_id=17,
            command_id=COMMAND_ID,
            result_code=0,
            completed_time_us=1_750_000,
            detail_code=0,
        )
    )

    arrays = "\n\n".join(
        (
            c_array("zs_command_vector_payload", payload),
            c_array("zs_command_vector_signed_cbor", signed_cbor),
            c_array("zs_command_vector_public_key", public_key),
            c_array("zs_command_vector_key_id", signer.key_id),
            c_array("zs_command_vector_signature", signature),
            c_array("zs_command_vector_ack", ack),
        )
    )
    return f"""/* Generated by tools/generate_mqtt_command_vector.py; do not edit. */
#ifndef ZS_COMMAND_VECTOR_H
#define ZS_COMMAND_VECTOR_H

#include <stdint.h>

#define ZS_COMMAND_VECTOR_STATION_ID UINT32_C(17)
#define ZS_COMMAND_VECTOR_CREATED_US UINT64_C(1000000)
#define ZS_COMMAND_VECTOR_EXPIRES_US UINT64_C(2000000)

{arrays}

#endif
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.stdout:
        sys.stdout.write(expected)
        return 0
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"generated command vector is stale: {OUTPUT}")
        print("MQTT command server/firmware vector: PASS")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
