#!/usr/bin/env python3
"""Shared vector for the firmware update over MQTT (MQTT ICD addendum F): a deterministic test image with its .fw_info
block, the release manifest signed by the repository test release key, the CMD_UPDATE_FIRMWARE envelope signed by
the command test key, the station's first fwreq and the server's three fw chunks.  firmware/tests/test_fw_update.c
checks them with the real Ed25519 backend and download engine; server/tests/test_firmware_update.py checks that the
generated header is current.  Public repository test material, never production keys."""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))
from station import firmware_codec as fw  # noqa: E402
from station.command_codec import CommandSigner, encode_signed_command  # noqa: E402
from station.schemas import StationCommand  # noqa: E402

OUTPUT = ROOT / "firmware" / "generated" / "zs_fw_update_vector.h"
COMMAND_SEED = bytes(range(1, 33))            # the command test key of generate_command_set_vector.py
RELEASE_SEED = bytes(range(65, 97))           # the release test key (addendum F), also the twin's
COMMAND_ID = "2b0f1c3a-0000-4000-8000-000000000007"
CREATED_US, EXPIRES_US = 1_800_000_000_000_000, 1_800_000_600_000_000
STATION_ID = 17
IMAGE_VERSION = 7
IMAGE_BYTES = 2600                            # three chunks: 1024 + 1024 + 552 (the tail pads a quad-word)


def test_image(version: int = IMAGE_VERSION, size: int = IMAGE_BYTES, target: int = fw.TARGET_STM32_APP) -> bytes:
    """Deterministic bytes (SHA-256 counter stream) with the .fw_info block at 0x400; the twin uses it too."""
    stream = b"".join(hashlib.sha256(b"dioneya-test-image" + i.to_bytes(4, "big")).digest() for i in range((size + 31) // 32))
    image = bytearray(stream[:size])
    image[fw.FW_INFO_OFFSET:fw.FW_INFO_OFFSET + fw.FW_INFO_BYTES] = fw.build_fw_info(target, version)
    return bytes(image)


def vector() -> dict[str, bytes]:
    release = fw.ReleaseSigner(Ed25519PrivateKey.from_private_bytes(RELEASE_SEED))
    image = test_image()
    manifest = fw.manifest_for_image(image).encode()
    signature = release.sign(manifest)
    command = StationCommand(command_id=COMMAND_ID, station_id=STATION_ID, command=fw.UPDATE_COMMAND,
                             payload=fw.command_payload(manifest, release.key_id, signature),
                             created_time_us=CREATED_US, expires_time_us=EXPIRES_US)
    envelope = encode_signed_command(command, CommandSigner(Ed25519PrivateKey.from_private_bytes(COMMAND_SEED)))
    cid = bytes.fromhex(COMMAND_ID.replace("-", ""))
    out = {
        "release_public_key": release.public_raw,
        "image": image,
        "manifest": manifest,
        "signature": signature,
        "command": envelope,
        "request0": fw.encode_request(fw.FirmwareRequest(STATION_ID, cid, 0, fw.CHUNK_BYTES)),
    }
    for i, offset in enumerate(range(0, len(image), fw.CHUNK_BYTES)):
        out[f"chunk{i}"] = fw.encode_chunk(STATION_ID, cid, offset, image[offset:offset + fw.CHUNK_BYTES])
    return out


def c_array(name: str, value: bytes) -> str:
    rows = [", ".join(f"0x{b:02x}u" for b in value[i:i + 16]) for i in range(0, len(value), 16)]
    return f"static const uint8_t {name}[{len(value)}] = {{\n    " + ",\n    ".join(rows) + "\n};"


def render() -> str:
    arrays = "\n\n".join(c_array(f"zs_fw_update_vector_{name}", value) for name, value in vector().items())
    return f"""/* Generated by tools/generate_fw_update_vector.py; do not edit. */
#ifndef ZS_FW_UPDATE_VECTOR_H
#define ZS_FW_UPDATE_VECTOR_H

#include <stdint.h>

#define ZS_FW_UPDATE_VECTOR_STATION_ID {STATION_ID}u
#define ZS_FW_UPDATE_VECTOR_VERSION {IMAGE_VERSION}u
#define ZS_FW_UPDATE_VECTOR_CREATED_US UINT64_C({CREATED_US})
#define ZS_FW_UPDATE_VECTOR_EXPIRES_US UINT64_C({EXPIRES_US})

{arrays}

#endif
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; run tools/generate_fw_update_vector.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
