#!/usr/bin/env python3
"""Shared vector for the addendum-D commands (CMD_REBOOT, CMD_SET_PARAMS): signed by the server codec with the
repository test key, decoded and verified by firmware/tests/test_command_set.c; the server test checks that the
generated header is current."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))
from station.command_codec import CommandSigner, encode_signed_command  # noqa: E402
from station.schemas import StationCommand  # noqa: E402

OUTPUT = ROOT / "firmware" / "generated" / "zs_command_set_vector.h"
# Public repository test material (same seed as generate_mqtt_command_vector.py); never a production key.
TEST_PRIVATE_SEED = bytes(range(1, 33))
REBOOT_ID = "2b0f1c3a-0000-4000-8000-000000000002"
PARAMS_ID = "2b0f1c3a-0000-4000-8000-000000000003"
CREATED_US, EXPIRES_US = 1_800_000_000_000_000, 1_800_000_600_000_000


def envelopes() -> tuple[bytes, bytes, bytes]:
    key = Ed25519PrivateKey.from_private_bytes(TEST_PRIVATE_SEED)
    signer = CommandSigner(key)
    reboot = encode_signed_command(StationCommand(command_id=REBOOT_ID, station_id=17, command="CMD_REBOOT",
                                                  payload={"delay_s": 30}, created_time_us=CREATED_US,
                                                  expires_time_us=EXPIRES_US), signer)
    params = encode_signed_command(StationCommand(command_id=PARAMS_ID, station_id=17, command="CMD_SET_PARAMS",
                                                  payload={"reset": False, "params": {"heartbeat_period_s": 3600, "mic_channel": 2, "listen_dwell_s": 5}},
                                                  created_time_us=CREATED_US, expires_time_us=EXPIRES_US), signer)
    public = key.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)
    return public, reboot, params


def c_array(name: str, value: bytes) -> str:
    rows = [", ".join(f"0x{b:02x}u" for b in value[i:i + 16]) for i in range(0, len(value), 16)]
    return f"static const uint8_t {name}[{len(value)}] = {{\n    " + ",\n    ".join(rows) + "\n};"


def render() -> str:
    public, reboot, params = envelopes()
    return f"""/* Generated by tools/generate_command_set_vector.py; do not edit. */
#ifndef ZS_COMMAND_SET_VECTOR_H
#define ZS_COMMAND_SET_VECTOR_H

#include <stdint.h>

#define ZS_COMMAND_SET_VECTOR_STATION_ID 17u
#define ZS_COMMAND_SET_VECTOR_CREATED_US UINT64_C({CREATED_US})
#define ZS_COMMAND_SET_VECTOR_EXPIRES_US UINT64_C({EXPIRES_US})

{c_array("zs_command_set_vector_public_key", public)}

{c_array("zs_command_set_vector_reboot", reboot)}

{c_array("zs_command_set_vector_params", params)}

#endif
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; run tools/generate_command_set_vector.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
