#!/usr/bin/env python3
"""Generate the EVT-PRE-20 STM32 target contract from locked Rev.A inputs."""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PIN_SOURCES = (
    "hardware/EVT_PRE_20_PIN_MAP_REV_A.csv",
    "hardware/AAD_CFG_PIN_ADDENDUM_REV_A.csv",
)
HEADER_PATH = "firmware/targets/evt_pre_20/include/evt_pre_20_board_pins.h"
CLOCK_HEADER_PATH = "firmware/targets/evt_pre_20/include/evt_pre_20_clock_policy.h"
MANIFEST_PATH = "firmware/targets/evt_pre_20/target_contract_manifest.json"

TARGET_ID = "dioneya_evt_pre_20_rev_a"
MCU = "STM32U585VIT6Q"
PACKAGE = "LQFP100_14x14"
PIN_DATABASE = "STM32U585VITxQ"
CLOCK_POLICY = "REV_A_INTERNAL_HSI_MSI_PLL_NO_HSE"
LOW_SPEED_REFERENCE = "SiT1552AI-JE-DCC-32.768D"
LOW_SPEED_REFERENCE_HZ = 32768

DIRECTION_ENUM = {
    "IN": "EVT_PRE_20_DIRECTION_IN",
    "OUT": "EVT_PRE_20_DIRECTION_OUT",
    "BIDIR": "EVT_PRE_20_DIRECTION_BIDIR",
    "OUT_OD": "EVT_PRE_20_DIRECTION_OUT_OD",
    "BIDIR_OD": "EVT_PRE_20_DIRECTION_BIDIR_OD",
}
SPECIAL_AF = {"GPIO": -1, "RCC": -2, "SYS": -3}


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def sha256_file(relative: str) -> str:
    return sha256_bytes((ROOT / relative).read_bytes())


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def read_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for relative in PIN_SOURCES:
        with (ROOT / relative).open(encoding="utf-8-sig", newline="") as source:
            rows.extend(csv.DictReader(source))
    return rows


def parse_gpio(value: str) -> tuple[str, int]:
    match = re.fullmatch(r"P([A-H])(\d{1,2})", value)
    if not match:
        raise ValueError(f"invalid MCU GPIO: {value}")
    pin = int(match.group(2))
    if pin > 15:
        raise ValueError(f"invalid MCU GPIO index: {value}")
    return match.group(1), pin


def parse_af(value: str) -> int:
    match = re.fullmatch(r"AF(\d{1,2})", value)
    if match:
        return int(match.group(1))
    if value in SPECIAL_AF:
        return SPECIAL_AF[value]
    raise ValueError(f"invalid alternate-function marker: {value}")


def validate_inputs(rows: list[dict[str, str]]) -> None:
    required_columns = {
        "Net",
        "Function",
        "MCU_Pin",
        "LQFP100_Pin",
        "CubeMX_Signal",
        "AF",
        "Direction_at_MCU",
    }
    if len(rows) != 65:
        raise ValueError(f"expected 65 locked pin assignments, got {len(rows)}")
    for column in required_columns:
        if any(not row.get(column) for row in rows):
            raise ValueError(f"missing required pin-map value: {column}")
    for key in ("Net", "MCU_Pin", "LQFP100_Pin"):
        values = [row[key] for row in rows]
        duplicates = sorted({value for value in values if values.count(value) > 1})
        if duplicates:
            raise ValueError(f"duplicate {key}: {duplicates}")
    for row in rows:
        parse_gpio(row["MCU_Pin"])
        package_pin = int(row["LQFP100_Pin"])
        if not 1 <= package_pin <= 100:
            raise ValueError(f"invalid LQFP100 pin: {package_pin}")
        parse_af(row["AF"])
        if row["Direction_at_MCU"] not in DIRECTION_ENUM:
            raise ValueError(f"invalid direction: {row['Direction_at_MCU']}")


def render_board_header(rows: list[dict[str, str]]) -> str:
    output = [
        "/* Generated by tools/generate_evt_pre_20_target_contract.py; do not edit. */",
        "#ifndef EVT_PRE_20_BOARD_PINS_H",
        "#define EVT_PRE_20_BOARD_PINS_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define EVT_PRE_20_TARGET_ID {c_string(TARGET_ID)}",
        f"#define EVT_PRE_20_MCU_MPN {c_string(MCU)}",
        f"#define EVT_PRE_20_MCU_PACKAGE {c_string(PACKAGE)}",
        f"#define EVT_PRE_20_PIN_DATABASE {c_string(PIN_DATABASE)}",
        f"#define EVT_PRE_20_PIN_ASSIGNMENT_COUNT {len(rows)}u",
        "#define EVT_PRE_20_AF_GPIO (-1)",
        "#define EVT_PRE_20_AF_RCC (-2)",
        "#define EVT_PRE_20_AF_SYS (-3)",
        "",
        "typedef enum {",
        "  EVT_PRE_20_DIRECTION_IN = 0,",
        "  EVT_PRE_20_DIRECTION_OUT,",
        "  EVT_PRE_20_DIRECTION_BIDIR,",
        "  EVT_PRE_20_DIRECTION_OUT_OD,",
        "  EVT_PRE_20_DIRECTION_BIDIR_OD",
        "} evt_pre_20_pin_direction_t;",
        "",
        "typedef struct {",
        "  const char *net;",
        "  const char *function;",
        "  char gpio_port;",
        "  uint8_t gpio_pin;",
        "  uint8_t lqfp100_pin;",
        "  const char *cubemx_signal;",
        "  int8_t alternate_function;",
        "  evt_pre_20_pin_direction_t direction;",
        "} evt_pre_20_pin_contract_t;",
        "",
        "static const evt_pre_20_pin_contract_t evt_pre_20_pin_contract[] = {",
    ]
    for row in rows:
        port, gpio_pin = parse_gpio(row["MCU_Pin"])
        alternate_function = parse_af(row["AF"])
        output.append(
            "  {"
            f"{c_string(row['Net'])}, {c_string(row['Function'])}, '{port}', {gpio_pin}u, "
            f"{int(row['LQFP100_Pin'])}u, {c_string(row['CubeMX_Signal'])}, "
            f"{alternate_function}, {DIRECTION_ENUM[row['Direction_at_MCU']]}"
            "},"
        )
    output.extend(
        [
            "};",
            "",
            "_Static_assert(",
            "    sizeof(evt_pre_20_pin_contract) / sizeof(evt_pre_20_pin_contract[0]) ==",
            "        EVT_PRE_20_PIN_ASSIGNMENT_COUNT,",
            '    "EVT-PRE-20 pin contract count mismatch");',
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(output)


def render_clock_header() -> str:
    return f"""/* Generated by tools/generate_evt_pre_20_target_contract.py; do not edit. */
#ifndef EVT_PRE_20_CLOCK_POLICY_H
#define EVT_PRE_20_CLOCK_POLICY_H

#include <stdint.h>

#define EVT_PRE_20_CLOCK_POLICY_ID {c_string(CLOCK_POLICY)}
#define EVT_PRE_20_EXTERNAL_HSE_ALLOWED 0
#define EVT_PRE_20_LOW_SPEED_REFERENCE {c_string(LOW_SPEED_REFERENCE)}
#define EVT_PRE_20_LOW_SPEED_REFERENCE_HZ UINT32_C({LOW_SPEED_REFERENCE_HZ})
#define EVT_PRE_20_RUNTIME_CLOCK_FREQUENCIES_RELEASED 0
#define EVT_PRE_20_RUNTIME_CLOCK_PROFILE_COUNT 5u

typedef enum {{
  EVT_PRE_20_CLOCK_PROFILE_S0_SLEEP = 0,
  EVT_PRE_20_CLOCK_PROFILE_S1_LISTEN,
  EVT_PRE_20_CLOCK_PROFILE_S2_DSP,
  EVT_PRE_20_CLOCK_PROFILE_S3_COMMS,
  EVT_PRE_20_CLOCK_PROFILE_S4_SERVICE
}} evt_pre_20_clock_profile_t;

_Static_assert(EVT_PRE_20_EXTERNAL_HSE_ALLOWED == 0,
               "EVT-PRE-20 Rev.A must not depend on external HSE");
_Static_assert(EVT_PRE_20_LOW_SPEED_REFERENCE_HZ == UINT32_C(32768),
               "EVT-PRE-20 low-speed reference mismatch");

#endif
"""


def render_manifest(board_header: bytes, clock_header: bytes) -> str:
    manifest = {
        "schema_version": 1,
        "configuration": "EVT-PRE-20",
        "target": {
            "target_id": TARGET_ID,
            "mcu": MCU,
            "package": PACKAGE,
            "exact_pin_database_ref": PIN_DATABASE,
        },
        "source_inputs": [
            {"path": relative, "sha256": sha256_file(relative)}
            for relative in (
                *PIN_SOURCES,
                "hardware/CLOCKING_REV_A.md",
                "firmware/targets/evt_pre_20/target_status.yaml",
            )
        ],
        "generated_outputs": [
            {"path": HEADER_PATH, "sha256": sha256_bytes(board_header)},
            {"path": CLOCK_HEADER_PATH, "sha256": sha256_bytes(clock_header)},
        ],
        "pin_assignment_count": 65,
        "clock_policy": {
            "policy_id": CLOCK_POLICY,
            "external_hse_allowed": False,
            "low_speed_reference": LOW_SPEED_REFERENCE,
            "low_speed_reference_hz": LOW_SPEED_REFERENCE_HZ,
            "runtime_frequencies_released": False,
        },
        "quality_gates": {
            "qg1_completeness": "tools/validate_evt_pre_20_target_contract.py",
            "qg2_technical": "tools/audit_evt_pre_20_target_technical.py",
        },
        "release_gate": {
            "status": "BLOCKED",
            "blockers": [
                "CUBEMX_IOC_MISSING",
                "STARTUP_MISSING",
                "LINKER_SCRIPT_MISSING",
                "HAL_LL_BINDINGS_MISSING",
                "SECURE_BOOT_MISSING",
                "OTA_AB_MISSING",
                "PRODUCTION_BUILD_MANIFEST_MISSING",
                "TARGET_HARDWARE_VALIDATION_MISSING",
            ],
        },
    }
    return json.dumps(manifest, indent=2, ensure_ascii=False) + "\n"


def expected_outputs() -> dict[str, str]:
    rows = read_rows()
    validate_inputs(rows)
    board = render_board_header(rows).encode("utf-8")
    clock = render_clock_header().encode("utf-8")
    return {
        HEADER_PATH: board.decode("utf-8"),
        CLOCK_HEADER_PATH: clock.decode("utf-8"),
        MANIFEST_PATH: render_manifest(board, clock),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if committed outputs are stale")
    args = parser.parse_args()

    outputs = expected_outputs()
    stale: list[str] = []
    for relative, expected in outputs.items():
        path = ROOT / relative
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != expected:
                stale.append(relative)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")

    if stale:
        print("EVT-PRE-20 target contract generation check: FAIL")
        for relative in stale:
            print(f"- stale or missing: {relative}")
        return 1
    action = "check" if args.check else "generation"
    print(f"EVT-PRE-20 target contract {action}: PASS ({len(read_rows())} pin assignments)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
