#!/usr/bin/env python3
"""Generate a deterministic server-to-firmware event receipt vector."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import sys

import cbor2


ROOT = Path(__file__).resolve().parents[1]
SERVER_ROOT = ROOT / "server"
OUTPUT = ROOT / "firmware" / "generated" / "zs_event_receipt_vector.h"
sys.path.insert(0, str(SERVER_ROOT))

from station.event_receipt_codec import EventReceipt, encode_event_receipt  # noqa: E402


def c_array(name: str, value: bytes) -> str:
    lines = []
    for offset in range(0, len(value), 12):
        chunk = ", ".join(f"0x{byte:02x}u" for byte in value[offset : offset + 12])
        lines.append(f"    {chunk},")
    return (
        f"static const uint8_t {name}[{len(value)}] = {{\n"
        + "\n".join(lines)
        + "\n};"
    )


def render() -> str:
    event_payload = cbor2.dumps(
        {
            0: 4,
            1: 2,
            2: 17,
            3: 5,
            4: 9,
            5: 42,
            6: 1_700_000,
            7: 0,
            8: {},
            10: {},
            12: {},
            13: {},
            14: {},
        },
        canonical=True,
    )
    digest = hashlib.sha256(event_payload).digest()
    receipt = encode_event_receipt(EventReceipt(17, 9, 5, 42, digest))
    arrays = "\n\n".join(
        (
            c_array("zs_event_receipt_vector_event_payload", event_payload),
            c_array("zs_event_receipt_vector_payload_sha256", digest),
            c_array("zs_event_receipt_vector_payload", receipt),
        )
    )
    return f"""/* Generated by tools/generate_event_receipt_vector.py; do not edit. */
#ifndef ZS_EVENT_RECEIPT_VECTOR_H
#define ZS_EVENT_RECEIPT_VECTOR_H

#include <stdint.h>

#define ZS_EVENT_RECEIPT_VECTOR_STATION_ID UINT32_C(17)
#define ZS_EVENT_RECEIPT_VECTOR_BOOT_ID UINT32_C(9)
#define ZS_EVENT_RECEIPT_VECTOR_SEQ_NO UINT32_C(5)
#define ZS_EVENT_RECEIPT_VECTOR_EVENT_ID UINT64_C(42)
#define ZS_EVENT_RECEIPT_VECTOR_EVENT_TIME_US INT64_C(1700000)

{arrays}

#endif
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"generated event receipt vector is stale: {OUTPUT}")
        print("MQTT event receipt server/firmware vector: PASS")
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
