#!/usr/bin/env python3
"""Shared vector for CMD_SET_NETWORK_CONFIG (MQTT ICD addendum G): the server codec signs a network configuration
patch (new server host and APN, version 2) with the repository test command key; firmware/tests/test_net_trial.c
decodes it with the real Ed25519 backend, applies the patch to the twin's version 1 record and drives the trial; the
server test checks that the generated header is current."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))
from station.command_codec import CommandSigner, encode_signed_command  # noqa: E402
from station.network_config import NETWORK_COMMAND, payload_to_wire  # noqa: E402
from station.schemas import StationCommand  # noqa: E402

OUTPUT = ROOT / "firmware" / "generated" / "zs_network_config_vector.h"
SEED = bytes(range(1, 33))                     # the test command key of generate_command_set_vector.py
COMMAND_ID = "2b0f1c3a-0000-4000-8000-000000000007"
CREATED_US, EXPIRES_US = 1_800_000_000_000_000, 1_800_000_600_000_000
PAYLOAD = {"version": 2, "server_host": "muhoed2.twin", "mqtt_port": 443, "apn1": "iot.pilot"}


def vector() -> dict[str, bytes]:
    key = Ed25519PrivateKey.from_private_bytes(SEED)
    command = StationCommand(command_id=COMMAND_ID, station_id=17, command=NETWORK_COMMAND, payload=PAYLOAD,
                             created_time_us=CREATED_US, expires_time_us=EXPIRES_US)
    return {
        "public_key": key.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw),
        "patch": payload_to_wire(PAYLOAD)[0],
        "command": encode_signed_command(command, CommandSigner(key)),
    }


def c_array(name: str, value: bytes) -> str:
    rows = [", ".join(f"0x{b:02x}u" for b in value[i:i + 16]) for i in range(0, len(value), 16)]
    return f"static const uint8_t {name}[{len(value)}] = {{\n    " + ",\n    ".join(rows) + "\n};"


def render() -> str:
    arrays = "\n\n".join(c_array(f"zs_network_config_vector_{name}", value) for name, value in vector().items())
    return f"""/* Generated by tools/generate_network_config_vector.py; do not edit. */
#ifndef ZS_NETWORK_CONFIG_VECTOR_H
#define ZS_NETWORK_CONFIG_VECTOR_H

#include <stdint.h>

#define ZS_NETWORK_CONFIG_VECTOR_STATION_ID 17u
#define ZS_NETWORK_CONFIG_VECTOR_CREATED_US UINT64_C({CREATED_US})
#define ZS_NETWORK_CONFIG_VECTOR_EXPIRES_US UINT64_C({EXPIRES_US})
#define ZS_NETWORK_CONFIG_VECTOR_VERSION {PAYLOAD["version"]}u
#define ZS_NETWORK_CONFIG_VECTOR_HOST "{PAYLOAD["server_host"]}"
#define ZS_NETWORK_CONFIG_VECTOR_MQTT_PORT {PAYLOAD["mqtt_port"]}u
#define ZS_NETWORK_CONFIG_VECTOR_APN1 "{PAYLOAD["apn1"]}"

{arrays}

#endif
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; run tools/generate_network_config_vector.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
