#!/usr/bin/env python3
"""Shared vector for the model package update (MQTT ICD addendum I): the manifest (target 3) of package m5 of the
built-in station model (firmware/generated/zs_model_centroids.h) signed by the repository test release key, the
CMD_UPDATE_FIRMWARE envelope signed by the command test key, the first fwreq, and feature vectors with the class the
Python mirror of the classifier (server/tools/export_station_model.py predict) gives them.  The package itself is not
in the header: firmware/tests/test_model.c builds it from the built-in table and checks that its SHA-256 is the one in
the signed manifest (the C and the Python encoder agree byte for byte), then runs it through the real parser, Ed25519
backend and download engine;
server/tests/test_model_update.py checks that the generated header is current.  Public test material only."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))
sys.path.insert(0, str(ROOT / "server" / "tools"))
from station import firmware_codec as fw  # noqa: E402
from station import model_codec as mc  # noqa: E402
from station.command_codec import CommandSigner, encode_signed_command  # noqa: E402
from station.schemas import StationCommand  # noqa: E402
import export_station_model as esm  # noqa: E402

OUTPUT = ROOT / "firmware" / "generated" / "zs_model_update_vector.h"
COMMAND_SEED = bytes(range(1, 33))            # the command test key of generate_command_set_vector.py
RELEASE_SEED = bytes(range(65, 97))           # the release test key of generate_fw_update_vector.py
COMMAND_ID = "2b0f1c3a-0000-4000-8000-000000000009"
CREATED_US, EXPIRES_US = 1_800_000_000_000_000, 1_800_000_600_000_000
STATION_ID = 17
MODEL_VERSION = 5
SAMPLE_CLASSES = 6                             # feature vectors near every n-th centroid


def builtin_model() -> dict:
    return esm.parse_header(esm.HEADER.read_text(encoding="utf-8"))


def samples(package: mc.ModelPackage) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Feature vectors a little off evenly spaced centroids (float32), the class and confidence u8 of the mirror."""
    n = package.class_count
    picks = np.linspace(0, n - 1, SAMPLE_CLASSES).round().astype(int)
    wiggle = np.array([((i * 7) % 11 - 5) / 50.0 for i in range(mc.FEATURE_COUNT)])
    model = package.as_model()
    z = model["centroids"][picks] + wiggle[None, :]
    features = (model["mean"] + z * (model["std"] + 1e-6)).astype(np.float32)
    class_id, conf = esm.predict(model, features.astype(np.float64))
    return features, class_id.astype(np.uint8), np.floor(conf * 255.0 + 0.5).astype(np.uint8)


def vector() -> dict:
    release = fw.ReleaseSigner(Ed25519PrivateKey.from_private_bytes(RELEASE_SEED))
    package_bytes = mc.encode_model(builtin_model(), MODEL_VERSION)
    manifest = mc.manifest_for_model(package_bytes).encode()
    signature = release.sign(manifest)
    command = StationCommand(command_id=COMMAND_ID, station_id=STATION_ID, command=fw.UPDATE_COMMAND,
                             payload=fw.command_payload(manifest, release.key_id, signature),
                             created_time_us=CREATED_US, expires_time_us=EXPIRES_US)
    envelope = encode_signed_command(command, CommandSigner(Ed25519PrivateKey.from_private_bytes(COMMAND_SEED)))
    cid = bytes.fromhex(COMMAND_ID.replace("-", ""))
    features, class_id, conf = samples(mc.parse_model(package_bytes))
    return {
        "bytes": {
            "release_public_key": release.public_raw,
            "manifest": manifest,
            "signature": signature,
            "command": envelope,
            "request0": fw.encode_request(fw.FirmwareRequest(STATION_ID, cid, 0, fw.CHUNK_BYTES)),
            "sample_class": bytes(class_id),
            "sample_conf": bytes(conf),
        },
        "features": features,
        "package_bytes": len(package_bytes),
    }


def c_array(name: str, value: bytes) -> str:
    rows = [", ".join(f"0x{b:02x}u" for b in value[i:i + 16]) for i in range(0, len(value), 16)]
    return f"static const uint8_t {name}[{len(value)}] = {{\n    " + ",\n    ".join(rows) + "\n};"


def c_float(v: np.float32) -> str:
    t = f"{float(v):.9g}"
    if "." not in t and "e" not in t:
        t += ".0"
    return t + "f"


def render() -> str:
    v = vector()
    arrays = "\n\n".join(c_array(f"zs_model_update_vector_{name}", value) for name, value in v["bytes"].items())
    rows = ",\n    ".join("{" + ", ".join(c_float(x) for x in row) + "}" for row in v["features"])
    return f"""/* Generated by tools/generate_model_update_vector.py; do not edit. */
#ifndef ZS_MODEL_UPDATE_VECTOR_H
#define ZS_MODEL_UPDATE_VECTOR_H

#include <stdint.h>

#define ZS_MODEL_UPDATE_VECTOR_STATION_ID {STATION_ID}u
#define ZS_MODEL_UPDATE_VECTOR_VERSION {MODEL_VERSION}u
#define ZS_MODEL_UPDATE_VECTOR_CREATED_US UINT64_C({CREATED_US})
#define ZS_MODEL_UPDATE_VECTOR_EXPIRES_US UINT64_C({EXPIRES_US})
#define ZS_MODEL_UPDATE_VECTOR_SAMPLES {SAMPLE_CLASSES}u
#define ZS_MODEL_UPDATE_VECTOR_PACKAGE_BYTES {v["package_bytes"]}u

{arrays}

static const float zs_model_update_vector_features[{SAMPLE_CLASSES}][{mc.FEATURE_COUNT}] = {{
    {rows}
}};

#endif
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; run tools/generate_model_update_vector.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
