#!/usr/bin/env python3
"""Shared vector for CMD_ROTATE_COMMAND_KEY (MQTT ICD addendum E): the server codec signs a rotation to the next test
key with the current test key, then a CMD_SET_PARAMS with the next key and a CMD_REBOOT with the current key;
firmware/tests/test_command_keys.c decodes them with the real Ed25519 backend (rotation, promotion, the old key
refused after it); the server test checks that the generated header is current."""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))
from station.command_codec import CommandSigner, encode_signed_command  # noqa: E402
from station.schemas import StationCommand  # noqa: E402

OUTPUT = ROOT / "firmware" / "generated" / "zs_command_rotate_vector.h"
# Public repository test material, never production keys: the current key is the seed of
# generate_command_set_vector.py, the next key the following 32 bytes.
CURRENT_SEED = bytes(range(1, 33))
NEXT_SEED = bytes(range(33, 65))
ROTATE_ID = "2b0f1c3a-0000-4000-8000-000000000004"
PARAMS_ID = "2b0f1c3a-0000-4000-8000-000000000005"
REBOOT_ID = "2b0f1c3a-0000-4000-8000-000000000006"
CREATED_US, EXPIRES_US = 1_800_000_000_000_000, 1_800_000_600_000_000


def raw_public(key: Ed25519PrivateKey) -> bytes:
    return key.public_key().public_bytes(serialization.Encoding.Raw, serialization.PublicFormat.Raw)


def vector() -> dict[str, bytes]:
    current = Ed25519PrivateKey.from_private_bytes(CURRENT_SEED)
    nxt = Ed25519PrivateKey.from_private_bytes(NEXT_SEED)

    def command(command_id: str, name: str, payload: dict) -> StationCommand:
        return StationCommand(command_id=command_id, station_id=17, command=name, payload=payload,
                              created_time_us=CREATED_US, expires_time_us=EXPIRES_US)

    return {
        "current_public_key": raw_public(current),
        "next_public_key": raw_public(nxt),
        "rotate": encode_signed_command(command(ROTATE_ID, "CMD_ROTATE_COMMAND_KEY", {"public_key": raw_public(nxt).hex()}),
                                        CommandSigner(current)),
        "params_by_next": encode_signed_command(command(PARAMS_ID, "CMD_SET_PARAMS", {"reset": False, "params": {"heartbeat_period_s": 900}}),
                                                CommandSigner(nxt)),
        "reboot_by_current": encode_signed_command(command(REBOOT_ID, "CMD_REBOOT", {"delay_s": 30}), CommandSigner(current)),
    }


def c_array(name: str, value: bytes) -> str:
    rows = [", ".join(f"0x{b:02x}u" for b in value[i:i + 16]) for i in range(0, len(value), 16)]
    return f"static const uint8_t {name}[{len(value)}] = {{\n    " + ",\n    ".join(rows) + "\n};"


def render() -> str:
    arrays = "\n\n".join(c_array(f"zs_command_rotate_vector_{name}", value) for name, value in vector().items())
    return f"""/* Generated by tools/generate_command_rotate_vector.py; do not edit. */
#ifndef ZS_COMMAND_ROTATE_VECTOR_H
#define ZS_COMMAND_ROTATE_VECTOR_H

#include <stdint.h>

#define ZS_COMMAND_ROTATE_VECTOR_STATION_ID 17u
#define ZS_COMMAND_ROTATE_VECTOR_CREATED_US UINT64_C({CREATED_US})
#define ZS_COMMAND_ROTATE_VECTOR_EXPIRES_US UINT64_C({EXPIRES_US})

{arrays}

#endif
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; run tools/generate_command_rotate_vector.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
