#!/usr/bin/env python3
"""Generate the shared audio-upload vector (MQTT_TLS_ICD_v0_1 addendum B): a 2-second 50 Hz tone at 1 kHz,
IMA-ADPCM encoded by the server mirror of the firmware encoder, and its single chunk.  The firmware test must
reproduce both byte-for-byte; the server test checks that this header is current."""
from __future__ import annotations

import argparse
import hashlib
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "server"))
from station.audio_chunk_codec import AudioChunk, CODEC_IMA_ADPCM_1S, encode_chunk, ima_encode_block  # noqa: E402

OUTPUT = ROOT / "firmware" / "generated" / "zs_audio_chunk_vector.h"
RATE, SECONDS = 1000, 2
COMMAND_ID = bytes(range(0x10, 0x20))
EVENT_ID = (5 << 32) | 42
START_US = 1800000120000000


def pcm() -> list[int]:
    return [int(12000.0 * math.sin(2.0 * math.pi * 50.0 * i / RATE)) for i in range(RATE * SECONDS)]


def segment() -> bytes:
    p = pcm()
    return b"".join(ima_encode_block(p[s * RATE:(s + 1) * RATE]) for s in range(SECONDS))


def chunk() -> bytes:
    seg = segment()
    return encode_chunk(AudioChunk(17, COMMAND_ID, EVENT_ID, 0, 0, 1, CODEC_IMA_ADPCM_1S, RATE, START_US, hashlib.sha256(seg).digest(), seg))


def c_array(name: str, value: bytes) -> str:
    rows = [", ".join(f"0x{b:02x}u" for b in value[i:i + 16]) for i in range(0, len(value), 16)]
    return f"static const uint8_t {name}[{len(value)}] = {{\n    " + ",\n    ".join(rows) + "\n};"


def render() -> str:
    seg = segment()
    return f"""/* Generated by tools/generate_audio_chunk_vector.py; do not edit. */
#ifndef ZS_AUDIO_CHUNK_VECTOR_H
#define ZS_AUDIO_CHUNK_VECTOR_H

#include <stdint.h>

#define ZS_AUDIO_CHUNK_VECTOR_RATE {RATE}u
#define ZS_AUDIO_CHUNK_VECTOR_SECONDS {SECONDS}u
#define ZS_AUDIO_CHUNK_VECTOR_EVENT_ID UINT64_C({EVENT_ID})
#define ZS_AUDIO_CHUNK_VECTOR_START_US INT64_C({START_US})

{c_array("zs_audio_chunk_vector_segment", seg)}

{c_array("zs_audio_chunk_vector_chunk", chunk())}

#endif
"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = render()
    if args.check:
        if OUTPUT.read_text() != text:
            print(f"{OUTPUT} is stale; run tools/generate_audio_chunk_vector.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
